### ISSUE TITLE
Uploading screenshots is broken in 0.5.0

### ISSUE THREAD

**Issue by andehen** [growthbook/growthbook#101]
Nothing happens when trying to uploading screenshots (see screenshot below). Works fine in 0.4.0, but not in 0.5.0.

![image](https://user-images.githubusercontent.com/754494/134691245-9846a3f8-4e17-42f6-bda5-b667a7e6bb86.png)

**Comment by jdorn** [comment]
Thanks for catching this.  Just pushed a fix.  Will take about 10 minutes for the Docker build to get updated

**Comment by andehen** [comment]
That was quick!

Awesome project btw, hope it takes off! 🚀
