### ISSUE TITLE
[Feature] add ability to reset password when logged in

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#1011]
Currently users cannot reset their password while logged in, and this causes confusion as they don't know how to get to the password reset flow

**Comment by shahpawann** [comment]
Here is the demo video where user can reset their password even they are logged in https://www.loom.com/share/09abac81291e42878de6ee9f26dcb091, 
may i could not get the scope of this issue, 
would you please elaborate the issue more clearly. 
Thanks

**Comment by Auz** [comment]
You are correct- the reset password doesn't show up for SSO users, but its not always clear that this is why. Closing for now
