### ISSUE TITLE
[Bug] Experiment can't be loaded in the UI after switching data source

### ISSUE THREAD

**Issue by rowolff** [growthbook/growthbook#1026]
### Summary

Some (not all) Experiments fail to load in the UI after switching the data source from e.g. Athena to Presto.

#### Expected Behavior

UI loads the experiment.

#### Current Behavior

UI fails to load with `Application error: a client-side exception has occurred (see the browser console for more information).`, the console shows that the call to the /organisation endpoint fails, because the auth header is just sent as `authorization: Bearer` and no value at all.

Experiments that were switched to the new data source correctly send the correct Auth header.

#### Steps to reproduce

1. change data sourced in metrics with importing config yaml
2. in experiment: update data -> error, since wrong data source was selected
3. change data source in experiment
4. add metrics in experiment
5. save => causes the error

**Comment by rowolff** [comment]
Update: over the weekend it seemingly fixed itself. The experiment is now available without errors.

**Comment by rowolff** [comment]
Another update: today it's broken again, after adding another guardrail. The error is the same, the organization call is made without a bearer token.

**Comment by tinahollygb** [comment]
The organization 401 error happens on every page on initial load. It should be unrelated. There's a ticket for it here: https://github.com/growthbook/growthbook/issues/972

Does the experiment still not load after switching data sources? Can you provide more info about this specific error? Is there anything in the console related to this specifically?

**Comment by rowolff** [comment]
Hi @tinahollygb , we didn't have the error for a while now - I will close this one and watch #1038 instead.

**Comment by tinahollygb** [comment]
Thanks for confirming @rowolff ... The 401 organizations error isn't related to your issue—it happens on every page load of every page. It's unfortunately a red herring that is often attributed to other issues that occur. If you do see another issue related to experiments not being able to be loaded, feel free to re-open and provide more information about that specifically.
