### ISSUE TITLE
[Bug] GET /organization always returns 401 on first load

### ISSUE THREAD

**Issue by tinahollygb** [growthbook/growthbook#1038]
This 401 Unauthorized that always gets returned on a hard refresh of the page is misleading when other errors occur, causing users to falsely report the cause of the error they're experiencing to this call.

## Acceptance Criteria

- The 401 error does not occur when there's a page reload—if we do not have a bearer token, do not send the request.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/113377031/222012326-914fc270-0438-443d-8038-6c56e3e6dc45.png">

**Comment by jdorn** [comment]
This was fixed
