### ISSUE TITLE
[Bug] Date Dimension displaying incorrect dates on the chart compared to query detail

### ISSUE THREAD

**Issue by markloomis32** [growthbook/growthbook#1065]
### Summary

When looking at the date dimension chart within an experiment analysis the dates are displaying incorrectly compared in the values shown by "view queries"
#### Expected Behavior

Dates in the chart should reflect the correct dates
#### Current Behavior

The dates display is 1 day less than it should be (March 6th is showing as March 6th)
<img width="417" alt="chart" src="https://user-images.githubusercontent.com/21222632/224363442-83a8cd51-fd53-451d-ae5b-bcc97d5fb946.png">

<img width="840" alt="table" src="https://user-images.githubusercontent.com/21222632/224363476-d270eac6-b80e-4c9c-a041-45139ba1a1c8.png">

**Comment by lukesonnet** [comment]
Thanks for reporting this Mark; this looks like a time zone issue. We need to update `getValidDate()` to handle conditions where there is no timezone or HMD data better.
