### ISSUE TITLE
[Feature] Frequentist inference in Jupyter Notebook Query Runner

### ISSUE THREAD

**Issue by websitelytics** [growthbook/growthbook#1068]
### Description of Feature

**Jupyter Notebook Query Runner**:  it would be great to have an option  getting results not only in Bayesian inference but also in Frequentist approach. It would be useful for those who prefer that method of statistical inference. And as Jupyter Query Runner allows you getting the exact digits of the stats this would be quite interesting feature.

### Related Issues

Currently there is only Bayesian statistics in Jupyter Notebook Query Runner available.

**Comment by lukesonnet** [comment]
Thanks for reporting this! This should have been closed by #1127
