### ISSUE TITLE
[Bug] Failed to fetch on a local enviroment.

### ISSUE THREAD

**Issue by onadjarj** [growthbook/growthbook#1069]
HI guysm i'm habing this issue, Failed to fetch on a local enviroment.
[image](https://user-images.githubusercontent.com/109534564/224584075-d720771b-dfcf-46c7-b7ee-b06b81c6c706.png)
Does anyone know if this is a bug or a way to solve the issue thanks a lot :D

**Comment by tinahollygb** [comment]
Closing this due to lack of information. If you'd like to get some help, feel free to [join our Slack](https://slack.growthbook.io/?ref=github-issue-1069 where someone can help.
