### ISSUE TITLE
Simplify variation id format

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#108]
We currently support two kinds of variation ids - array index and string keys. With the recent change in #97 we no longer need both options and can just use string keys for everyone.  This data source option is hard to explain in the UI and docs, so removing it will be good.

TODO:
- Remove from data source form
- Remove from data source info page
- Simplify logic in front-end wherever variationIdFormat was being used
- Simplify logic in back end wherever it was being used
- Testing all edge cases
- Update docs

**Comment by deepto98** [comment]
@jdorn Hi, I'd like to work on this issue. If it isn't assigned already, can you please assign this to me?
