### ISSUE TITLE
[Feature] Disable stats engine on all control variations

### ISSUE THREAD

**Issue by dustinblackman** [growthbook/growthbook#1082]
### Description of Feature

I run experiments with multiple control groups to assist in verifying I'm measuring correctly, where two controls should measure the same. Unfortunately the stats engine kinda gets in the way in an experiment's results breakdown.

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/5246169/225452323-dbe0341f-628d-4338-b13b-c94e27d8e3f2.png">

I have a [hacky solution](https://github.com/dustinblackman/growthbook/commit/c0fa4370beb336395e83235f39a8e2bcc017e6b0) to manage this for my personal case that has the results graph look like this where all control variations don't show `chance to beat control` and `percent change` columns.

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/5246169/225452403-b4d1ce7f-b744-43c0-b0d9-bf1a0e4a32f7.png">

Would it be within the boundaries of the project to mark a variation during experiment creation as a `control group` to exclude it from components such as the stats engine, rather than it just being the first variation?

**Comment by lukesonnet** [comment]
Hmm, this is a pretty cool way to embed an A/A test right in your A/B test and get a succinct report on whether it worked (although I would add some custom stats between the two controls to check they are equal :) ). I like it a lot.

I'm not sure if it makes sense for us to build out a bunch of custom logic to handle it, however. I think we are planning later in the year to work on redoing some of the UI to make it better for the case with multiple variations (see #599 ), and maybe if whatever our final design for that solution ends up being doesn't work for your use case, we can revisit supporting this more explicitly.

**Comment by lukesonnet** [comment]
We probably won't build this custom logic in the near future, but our new experiment results view should make it easier to only look at certain variants and even change the baseline!
