### ISSUE TITLE
[Feature] Cancel Queries in Snowflake from GrowthBook

### ISSUE THREAD

**Issue by juliannaharwood** [growthbook/growthbook#1091]
### Description of Feature

The desired state is when a user cancels an in-progress data refresh in GrowthBook, it also cancels the Snowflake queries that were started. Currently, cancelling in GrowthBook only stops the UI from updating. A user needs to manually cancel all of the Snowflake queries in order to actually stop them from running.

**Comment by lukesonnet** [comment]
We agree this could be improved. Closing as a duplicate of #310
