### ISSUE TITLE
Any examples how to force backend feature across requests for same user? (API testing)

### ISSUE THREAD

**Issue by Xotabu4** [growthbook/growthbook#1172]
This question is related to API testing using the JavaScript SDK, specifically on how to force a backend feature across requests for the same user. The scenario may involve a backend feature that is only activated once for a user, and you need to ensure that it stays activated for subsequent requests made by the same user.

**Comment by tinahollygb** [comment]
Yes, we have some JavaScript examples here: https://github.com/growthbook/examples

Provided you use the same hash attribute and hash version, your features should be evaluated the same on all implementations.

You can read more about targeting attributes [here](https://docs.growthbook.io/lib/js#attributes).
