### ISSUE TITLE
[Bug] Images uploaded for variations on the experiment page can intermittently break

### ISSUE THREAD

**Issue by lukesonnet** [growthbook/growthbook#1183]
### Summary

Some customers are experiencing intermittent issues where sometimes an image uploaded to an experiment page is breaking at times.

#### Expected Behavior

The images should upload and persist.

**Comment by mknowlton89** [comment]
@lukesonnet Do you recall which organizations were experiencing this? And do you know if they were using the standard storage, or if they're using S3 or something else? Thanks!
