### ISSUE TITLE
Queries throw error when breaking out analysis by custom dimension[Bug] 

### ISSUE THREAD

**Issue by chloedevriesclue** [growthbook/growthbook#1197]
### Summary

When you try to run an an experiment analysis broken out by a custom dimension that is created from the Experiment Assignment query, the query throws an error. I believe this is due to misuse of a CONCAT() function (using Redshift).

#### Expected Behavior

The experiment analysis queries should run without erroring out.

#### Current Behavior

There are two ways to build custom dimensions - they can be built in the "Dimensions" tab of the UI via a separate query, or can be built into the experiment assignment query. For the experiment I am currently working on, we need to use the experiment assignment query because the dimension changes over time for the user.

When you set the analysis to use a dimension that is built in the experiment assignment query, all of the queries throw an error.

![image](https://user-images.githubusercontent.com/99745893/232782899-8868d43c-2ab1-49d7-b313-a5933605d9c6.png)
![image](https://user-images.githubusercontent.com/99745893/232782934-cf572b2b-a6b5-4cd7-b554-04345f80b1b9.png)

It looks like the query tries to concatenate 3 things by using `CONCAT(str1, str2, str3)`, but in Redshift the function only takes two arguments, so you instead have to do `CONCAT(str1, CONCAT(str2, str3))`. When I make this update and run the query externally, it works and returns accurate results.

**Comment by lukesonnet** [comment]
Hi Chloe!

Thanks for reporting this bug. We should have fixed this in a recent PR (https://github.com/growthbook/growthbook/pull/1184)

Are you on self-hosted what is your build number (in the bottom left of the growthbook app), and if so can you upgrade?

**Comment by chloedevriesclue** [comment]
Hi Luke,

Thanks for responding so quickly! It looks like we're on build f58a91e.
Assuming that's not the most recent build, I'll chat with our ops folks
about updating tomorrow.

Best,
Chloe

**Comment by chloedevriesclue** [comment]
Hey Luke,

It seems like this is the most recent build - it looks like your PR hasn't
been part of an actual release yet? Is that something we need to wait for?
Or should we be able to incorporate these changes pre-emptively?

Chloe

**Comment by lukesonnet** [comment]
Hi Chloe, you might have the latest build for version 2.0. You might need to change your version to `latest` and then update to get this fix, or you'll have to wait until 2.1 is released (in May) and upgrade to that.

**Comment by lukesonnet** [comment]
To clarify, we released this fix *after* the 2.0 release. If your version is set to 2.0, you won't get the features/commits that landed after the 2.0 release. The build you sent me is 3 weeks old, from the 2.0 release. `latest` will get you the latest commits whenever you update, regardless of version.

**Comment by chloedevriesclue** [comment]
Got it, thanks. We got it figured out today :) thanks for the help!

Best,
Chloe
