### ISSUE TITLE
[Feature] Open experiments and metrics in a new tab from the list

### ISSUE THREAD

**Issue by xgumara** [growthbook/growthbook#1203]
### Description of Feature

From the list of experiments (and metrics) I would love to be able to command-click (Mac) (or Ctrl-click in Windows) an experiment and/or metric from the list for it to open in a new tab. Right button and "Open in a new tab" would be very nice too.

**Comment by jdorn** [comment]
The experiment/feature names are links and you should be able to open in a new tab via any of the methods you mention.
