### ISSUE TITLE
[Bug] custom domain with istio in front on kubernetes, the api itself keeps redirecting to request_uri:3100 instead of the configured request_uri/api

### ISSUE THREAD

**Issue by mayag1234** [growthbook/growthbook#1217]
### Summary
When using custom domain with istio infront on kubernetse, the api itself keeps redirecting to request_uri:3100 instead of the configured request_uri/api

Due to security reasons we have ports 3000 and 3100 on the cluster disabled. We use istio to route the traffic to these ports and in the deployment definition we have defined the following:
growthbookConfig:
  APP_ORIGIN: "https://example.com/"
  API_HOST: "https://example.com/api"

The env variables in the pod that is being created are correct but when we try to access the ui it shows as loading. When we try to access the api it shows the following:
http://example.com:3100

The expected behavior is to not use port 3100 when the above definition is being done.

**Comment by tinahollygb** [comment]
We do not currently support running the front-end and the back-end both on the same port. Our front-end has its own set of `/api` routes. They will need to be different ports for this to work. We will be updating the documentation and debugging data at the endpoint `GET /` to reflect this.
