### ISSUE TITLE
[Bug] 'Targeting Conditions' does not work using 'does not include' in many conditions

### ISSUE THREAD

**Issue by Maciej-Monster** [growthbook/growthbook#1225]
### Summary

Goal: create a rule which has 2+ more conditions `does not include` for an attribute which is a list of strings

Steps to reproduce:
1. Add a new `forced value` where an attribute is a list of strings.
2. Use `does not include`
3. Add another condition and also use `does not include` for the same attribute.

https://user-images.githubusercontent.com/118315970/234231550-63ecf378-d3dd-4778-81bd-cb48f5c0d58c.mp4

#### Expected Behavior

Two conditions should be added and be visible.

#### Current Behavior

Only one condition is applied and the other one is removed.

**Comment by jdorn** [comment]
Thanks for reporting this.  So it sounds like you basically want to do an intersection between two lists.  There's a workaround using the "advanced mode":

```json
{
  "user_ids": {
    "$not": {
      "$elemMatch": {
        "$in": ["Q", "W"]
      }
    }
  }
}
```

The way to read this is:
> `user_ids` does not contain an element that matches one of the specified values.

This workaround should work today, but there are 2 things we can do on our end to make this easier in the future:
1. Don't allow saving the form if there are conflicting conditions that will overwrite each other
2. Add support for this "intersection" behavior in the simple mode, so you don't have to write JSON

**Comment by katsadim** [comment]
Although the workaround in advanced mode works ok, I cannot really ask my project manager to start learning this kind of thing. Would it be possible for this to be fixed in the UI?
