### ISSUE TITLE
[Bug] Experiments are not updated automatically

### ISSUE THREAD

**Issue by KRLY05** [growthbook/growthbook#1237]
### Summary
Within settings it is possible to set up auto update of experiments, either via cron schedule, or when results are X hours old
However neither of this is performing autoupdate on the new version of growthbook (after v2.0.0 at least)
<img width="561" alt="image" src="https://user-images.githubusercontent.com/16836553/235026149-b02d2b16-ea14-4a22-9808-e3c0a10b521e.png">

#### Expected Behavior

when `cron schedule` is enabled, experiments are updated at the given time
when `when results are X hours` enabled, experiments are updated accordingly

#### Current Behavior

no autoupdate is happening, only manual

**Comment by jdorn** [comment]
Which build are you running? This was fixed recently in #1208

**Comment by lukesonnet** [comment]
While improvements around experiment refresh are on our radar, we aren't seeing this issue widespread at the moment, so I'm closing this as stale. Feel free to re-open with additional context if you are still having this issue. Thanks!
