### ISSUE TITLE
[Bug] New User Dimension layoffer "Edit SQL" misses date as required dimension

### ISSUE THREAD

**Issue by tim06927** [growthbook/growthbook#1253]
### Summary

When adding a new user dimension the "Edit SQL" states that it requires 2 fields (value and user id). Queries based on this fail.

#### Expected Behavior

The page should ask for all 3 required fields, including date.

#### Current Behavior

Queries fail.

**Comment by mknowlton89** [comment]
@tim06927 Are you still experiencing this? I just tried to replicate on the latest version and I was able to build a dimension with only `value` and `user_id`.
