### ISSUE TITLE
[Bug] Unrecognized key(s) in object: 'sseEnabled'

### ISSUE THREAD

**Issue by actalexandre** [growthbook/growthbook#1255]
### Summary

Fresh new instance with docker compose, growthbook version 2.1.0 :

```
# docker-compose.yml
version: "3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  growthbook:
    image: "growthbook/growthbook:2.1.0"
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/

    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
```

When selecting a SDK connection :

![image](https://user-images.githubusercontent.com/131654253/236305679-79780f93-150a-427f-ab14-d8868fd3f5a8.png)

#### Expected Behavior

Display SDK connection 

#### Current Behavior

Not displaying configuration, shows this error 

```
[
{
"code": "unrecognized_keys",
"keys": [
"sseEnabled"
],
"path": [],
"message": "Unrecognized key(s) in object: 'sseEnabled'"
}
]
```

**Comment by jessezhang91** [comment]
I am also seeing this w/ a fresh 2.1.0. i downgraded to 2.0.0 and it seemed to work fine afterwards
