### ISSUE TITLE
Remote evaluation

### ISSUE THREAD

**Issue by kalloc** [growthbook/growthbook#1277]
### Description of Feature

Possibility to pass context to GB API and receive only passed features.

https://openfeature.dev/blog/catering-to-the-client-side/#eager-evaluation-for-remote-evaluated-systems

I need to use much more data thane I can pass to context, so, proper client (browser/mobile) do not know enough data to resolve features map

Is there any plan to support remove evaluation?

**Comment by bryce-fitzsimons** [comment]
Hi @kalloc, remote evaluation is indeed in the works 😄

**Comment by lukesonnet** [comment]
Remote eval supported now for our front-end SDKs in #1294
