### ISSUE TITLE
[Bug] TypeError: Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by tabz24** [growthbook/growthbook#1297]
### Summary

I did the self-host setup of Growthbook using documentation. I added the data source of postgres and created an A/B experiment but the experiment is not loading. The page says An unexpected error has occurred.

#### Expected Behavior

Experiment should load

#### Current Behavior
Current settings for experiment
<img width="1013" alt="Screenshot 2023-05-23 at 13 12 39" src="https://github.com/growthbook/growthbook/assets/19698558/68153050-c82a-461e-937f-dad950d9ba0a">

Console log error
<img width="642" alt="Screenshot 2023-05-23 at 13 03 23" src="https://github.com/growthbook/growthbook/assets/19698558/548672a6-4fdf-437f-84ea-a6163aa59c63">
0764ae6d">

The code where it's actually failing
```
function p(e, n, t) {
            var r, i, a = (null === e || void 0 === e || null === (r = e.queries) || void 0 === r ? void 0 : r.exposure) || [];
            return n || (n = "user" === t ? "user_id" : "anonymous_id"),
            null !== (i = a.find((function(e) {
                return e.id === n
            }
            ))) && void 0 !== i ? i : null
        }
```
`e.id === n` returns `false` since `e.id` is `undefined`

Is this a bug or am I missing something?

**Comment by lukesonnet** [comment]
Closing this as stale. Looks like some bug but if it is still occurring please share the screenshot of the page that it is occurring on along with your `Experiments` page. Thank you!
