### ISSUE TITLE
[Bug] Kubernetes deployment - Error connecting to the GrowthBook API

### ISSUE THREAD

**Issue by aab-saphir** [growthbook/growthbook#1303]
### Summary

I deployed growthbook container on k8s cluster. I am exposing port 3000 and 3100 through ClusterIP. In my cluster, there is also an ingressroute to route external request to the service port 3000 with an URL. In my pod, I have response from port 3000 and 3100 with `curl localhost:3000` and `curl localhost:3100`. 

The env are defined this way :
```
APP_ORIGIN: 'http://localhost:3000'
API_HOST: 'http://localhost:3100'
```

#### Current Behavior

However, when I request the front application using URL from outside the cluster, I get a Growthbook API error:

![image](https://github.com/growthbook/growthbook/assets/124154176/60afd5ba-e0df-493b-ad6a-ad12c9b4c277)
The back respond with the following:
```
{
  "name": "GrowthBook API",
  "production": false,
  "api_host": "http://localhost:3100",
  "app_origin": "http://localhost:3000",
  "config_source": "db",
  "email_enabled": false,
  "build": {
    "sha": "",
    "date": ""
  }
}
```
This is the current behavior. 

#### Expected Behavior

In local with docker compose up -d, it works. The front return the image below:

![image](https://github.com/growthbook/growthbook/assets/124154176/3249579a-76b0-42ba-9ee0-10427160dd9e)

I would like to have the same front in my k8s deployment.

**Comment by aab-saphir** [comment]
Problem is solved. I have two url exposing the application on port 3000 (for front) and port 3100 (for back). My error was CORS access. The back URL pointed correcly to the port 3100 of the application. However external access were restricted. Adding this env solved my problem `CORS_ORIGIN_REGEX: '.*'` 
Also do not forget to add those env `JWT_SECRET` and `ENCRYPTION_KEY`.

**Comment by robertpro** [comment]
@aab-saphir Can you share the k8s scripts? I'm getting started with k8s and need to deploy growthbook
