### ISSUE TITLE
[Bug] Minor UI Bug: SRM error message shows the same ratio as "expected" and "observed" split in large data sets

### ISSUE THREAD

**Issue by tim06927** [growthbook/growthbook#1305]
### Summary

The SRM warning is irritating as "expected" and "observed" split appear to be the same, even though they are not.

#### Expected Behavior

Less rounding if the splits are very similar?

#### Current Behavior

The UI shows the same ratio as "expected" and "observed" split, because the mismatch is in the 5th decimal place only (in our case 0.90003). This message comes from a test with 20mio users.
![image](https://github.com/growthbook/growthbook/assets/25033213/22c2cc7b-416c-4fcd-88fa-3c2e52d55a0d)

**Comment by teamteak** [comment]
We are also getting this error.
