### ISSUE TITLE
[Bug] No p-values for metrics with small base rate in large experiments (Frequentist Stats)

### ISSUE THREAD

**Issue by tim06927** [growthbook/growthbook#1320]
### Summary

Using the Frequentist Stats engine (independent of MHC or CUPED) no p-values are displayed for some metrics. The parameters for this bug to appear that we could establish are (1) large experiment, (2) small base rate of the metric, and (3) large treatment effect.

#### Expected Behavior

p-values for all metrics.

#### Current Behavior

As visible in the screenshot below no p-values are displayed for significant changes with a small base rate and large treatment effects.

Numbers and texts are edited for business reasons, the rough dimension is correct.
![image](https://github.com/growthbook/growthbook/assets/25033213/0b3f1696-cbda-4743-812d-b3e5338cf87f)

**Comment by lukesonnet** [comment]
@tim06927 what version of Growthbook are you on?

I believe that should have been fixed in this PR: https://github.com/growthbook/growthbook/pull/1296
