### ISSUE TITLE
[Feature] one REST API to update single feature

### ISSUE THREAD

**Issue by grimmer0125** [growthbook/growthbook#1322]
### Description of Feature

I saw there is some internal API that people can use to update a feature, [here](https://github.com/growthbook/growthbook/blob/main/packages/back-end/src/app.ts#L462). It will be great if we can use an API key with REST API to do the same thing.

**Comment by hoseinmont** [comment]
+1

**Comment by lukesonnet** [comment]
A variety of REST API feature endpoints now exist! https://docs.growthbook.io/api#tag/features/operation/updateFeature
