### ISSUE TITLE
[Feature] Scoped API keys

### ISSUE THREAD

**Issue by PKolmanExt** [growthbook/growthbook#1328]
### Description of Feature

Hi, could you add scoped API keys? 
Right now all generated API keys have the admin access to the whole API. 

### Reason
My problem is that users with experimenter role can work with visual editor only with the API key that cannot be generated by this experimenter. It needs to be generated from the admin role and there is no permission limitation or scope. You basically give the experimenter role API key with full admin privileges. Why do these roles exist if you cannot use them properly with properly scoped API key? 

Same applies with multiple services. Right now its not possible to give some "cachingService" permission to read only. 

### Related Issues

I haven't found any issues related to this yet

**Comment by tinahollygb** [comment]
closed by https://github.com/growthbook/growthbook/pull/1265 – you can now create a personal access token as an experimenter, or an org-level read-only token if you're an admin.
