### ISSUE TITLE
[Feature] Add CI boundary values to the frequentist view 

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#1337]
We currently calculate but do not show the CI boundary values on the frequentist results. It would be good if we can figure out a way to show this somewhere. 

<img width="1319" alt="Screen Shot 2023-06-07 at 11 20 32 AM" src="https://github.com/growthbook/growthbook/assets/46107/4c89bf8f-fd9e-4044-a364-8e7909dbe937">

**Comment by lukesonnet** [comment]
They are in the tooltip in the new view. Closing this.
