### ISSUE TITLE
[Feature] (Fact) Metric update & delete APIs

### ISSUE THREAD

**Issue by itsgrimetime** [growthbook/growthbook#1342]
### Description of Feature

There are currently APIs for creating and getting metrics, but not for updating or deleting them. My team is building some tooling to sync our internal metrics definitions to GrowthBook and we want to ideally be able to update the configuration of individual metrics, or create new ones and delete the old ones.

**Comment by lukesonnet** [comment]
Leaving this open because we also need to create these endpoints for the newly launched Fact Metrics.

**Comment by lukesonnet** [comment]
Closed by #2054
