### ISSUE TITLE
[Feature] Multi-armed bandits

### ISSUE THREAD

**Issue by dbalabka** [growthbook/growthbook#1374]
### Description of Feature

Some other feature management systems enable us to implement features using [Multi-Armed Bandits](https://en.wikipedia.org/wiki/Multi-armed_bandit). It would be fantastic to have this capability included in Growthbookt as well. 

References:
1. https://ax.dev/docs/banditopt.html

**Comment by lukesonnet** [comment]
Thank you for opening this issue! We're unlikely to implement bandits in the near term, but we're aware of the value of bandits and hope to get there at some point.
