### ISSUE TITLE
[Feature] Add package to get prometheus metrics

### ISSUE THREAD

**Issue by AmirSalakhov94** [growthbook/growthbook#1401]
### Description of Feature

Could you please assist me with how to configure metrics in Growthbook itself? For example, for Prometheus, in order to create dashboards in Grafana and view metrics.

### Related Issues

**Comment by jdorn** [comment]
Are you trying to monitor a self-hosted GrowthBook instance using Prometheus?  Or trying to use data in Prometheus within GrowthBook for A/B testing?

**Comment by AmirSalakhov94** [comment]
Hi) We want to monitor a self-hosted GrowthBook instance using Prometheus.

**Comment by jdorn** [comment]
We just added support recently for OpenTelemetry - https://docs.growthbook.io/self-host/env#observability-opentelemetry

So with an OpenTelemetry collector, you should be able to send self-hosted GrowthBook metrics into Prometheus.

**Comment by AmirSalakhov94** [comment]
@jdorn hi) thanks, we tried to connect the collector and now we get span metrics from growthbook, but what about growthbook proxy? I see a [pull request](https://github.com/growthbook/growthbook-proxy/pull/25), but when will it be merged?
