### ISSUE TITLE
[Bug] TypeScript: Type expected.

### ISSUE THREAD

**Issue by Hephaest** [growthbook/growthbook#1430]
### Summary
Failed to compile.
```js
TypeScript error in /XXX/node_modules/@growthbook/growthbook/dist/types/growthbook.d.ts(188,37):
Type expected.  TS1110

    186 | export declare type ApiHost = string;
    187 | export declare type ClientKey = string;
  > 188 | export declare type RepositoryKey = `${ApiHost}||${ClientKey}`;
        |                                     ^
    189 | export declare type LoadFeaturesOptions = {
    190 |     autoRefresh?: boolean;
    191 |     timeout?: number;
```
#### Expected Behavior

No compile issue

#### Environment Information

| Package Name  | Package Version |
| ------------- | ------------- |
| node  | 12  |
| typescript  | 3.8  |
| @growthbook/growthbook  | 0.27.0  |
| @growthbook/growthbook-react  | 0.17.0  |

**Comment by Hephaest** [comment]
For anyone who encounters such an error, here is a workaround: https://www.npmjs.com/package/patch-package.

**Comment by aminesafi8** [comment]
This issue was fixed started from version 

@growthbook/growthbook | 0.28.0
-- | --


The issue can be closed.
