### ISSUE TITLE
[Feature] Sticky column headers for features list

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#1454]
Right now, if you have a lot of features on the feature listing page, when you scroll, you lose the context for the column names. It would be good to have the column names be sticky.

**Comment by eshwarhs** [comment]
Hi, I'd like to take this up.

**Comment by eshwarhs** [comment]
Hi, can I take this up?

**Comment by Satyam-G5** [comment]
Hi there! I'm interested in working on this issue. Could it be assigned to me, please? Thank you!

**Comment by Satyam-G5** [comment]
@Auz is the PR good enough to merge or need some changes ?
