### ISSUE TITLE
[Feature]  Add vertica as metrics backend

### ISSUE THREAD

**Issue by etg-ivan-chernov** [growthbook/growthbook#1469]
### Description of Feature

HP Vertica is a general column storage for Data Lake. It has an SQL interface, and can be used as metrics storage. Can you add integration with it?

### Related Issues

None

**Comment by mknowlton89** [comment]
Hey, @etg-ivan-chernov!

Thanks for submitting - I'll discuss this with the team at our next planning session.

**Comment by etg-ivan-chernov** [comment]
Are there any news?

**Comment by etg-ivan-chernov** [comment]
Thank you!
