### ISSUE TITLE
[Bug] Query errors hidden on ad-hoc report page

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#1470]
### Summary

Query errors are only visible on ad-hoc report pages when the View Queries modal is open.  Otherwise, there is no indication on the page that a problem occurred.

If `report.error` is set, we should show it prominently on the page at all times.

**Comment by mknowlton89** [comment]
@jdorn Do you feel this treatment is prominent enough?
<img width="1061" alt="Screen Shot 2023-07-24 at 2 29 26 PM" src="https://github.com/growthbook/growthbook/assets/75274610/69519472-4d64-42d5-993d-5c400e77dfa0">

<img width="1057" alt="Screen Shot 2023-07-24 at 2 30 18 PM" src="https://github.com/growthbook/growthbook/assets/75274610/b526e09f-1e0b-4d95-8e70-b5000ed087ef">

**Comment by lukesonnet** [comment]
@mknowlton89 I think the issue is this one: https://www.loom.com/share/019e5f78ae944979ad5257eeaa08b7b0

On the report page itself, we don't surface query errors anywhere other than if you click the three dots and open `View Queries`

**Comment by mknowlton89** [comment]
@lukesonnet Ah - thank you!

So, in the event of a `report.error` we'd want to showing something like....

<img width="1004" alt="Screen Shot 2023-07-25 at 2 49 53 PM" src="https://github.com/growthbook/growthbook/assets/75274610/6f1f51e1-98fd-436e-baa5-6e929c345b0b">
