### ISSUE TITLE
[Feature] As an analyst, I'd like to add quickview metrics to the experiments list, so I don't have to click into each one

### ISSUE THREAD

**Issue by clairengibbons** [growthbook/growthbook#1485]
### Description of Feature

- on the Experiments page where there is a list of all experiments with columns for tags, owner, phase, etc
- I'd like to see two more columns for the project designated north star metric: one for chance to beat control, and one for percent difference. Or for an experiment-level designated metric. Either one could work
- this would allow me to quickly scan experiment results without clicking into each one

**Comment by lukesonnet** [comment]
> I'd like to see two more columns for the project designated north star metric: one for chance to beat control, and one for percent difference

I think in the short run it would have to choose either (a) the first metric added to the experiment or (b) the first metric added to the project as a north star. Because there can be multiple metrics, I think I'd prefer if we just show one metric and we don't currently have a privileged metric status that can only have one metric.

**Comment by lukesonnet** [comment]
Hi! This is now available if you go to the Metric or Fact Metric page and click the "Experiments" tab. More improvements are planned to this list.

<img width="1628" alt="Screenshot 2024-09-11 at 10 05 26 AM" src="https://github.com/user-attachments/assets/5af36640-603b-4fb1-bc88-0b45baf0f43c">

**Comment by clairengibbons** [comment]
hi @lukesonnet thanks for the update, very cool! It doesn't seem like I have this view on my end (this is a metric in many experiments). Perhaps I need to opt-in somehow?

<img width="1071" alt="image" src="https://github.com/user-attachments/assets/8221ff78-4ed6-457b-b8cc-0d568256f7fc">
