### ISSUE TITLE
[Feature] Add REST API support for adding/updating feature flag force rules

### ISSUE THREAD

**Issue by mknowlton89** [growthbook/growthbook#1513]
### Description of Feature

An organization in our user Slack requested the ability to programmatically create/update feature flags with targeting conditions via the REST Api.

We'll want to think about how we can do this in a safe manner - the rules for a particular feature flag are environment specific, and are an array of rule objects, where the `conditions` are json, so it'd be very easy to make a mistake. The condition keys are also dependent on the user dimensions.

Slack chat - https://growthbookusers.slack.com/archives/C01T6PKD9C3/p1690392841711829

**Comment by jdorn** [comment]
Feature REST endpoints are live now
