### ISSUE TITLE
Add tooltip to dashboard graph

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#154]
The dashboard shows a graph of experiments started per month over the last year.  Show a tooltip on mouse over that shows the number of experiments using the visx tooltip component:
<img width="142" alt="Screen Shot 2021-11-11 at 12 08 59 PM" src="https://user-images.githubusercontent.com/46107/141362192-be273bb5-ff80-48c8-8f4e-4598a24791ba.png">

**Comment by lukesonnet** [comment]
Yep, thank you!
