### ISSUE TITLE
[Bug] Empty create experiment modal

### ISSUE THREAD

**Issue by tinahollygb** [growthbook/growthbook#1547]
When adding an experiment, it looks like this:

![image](https://github.com/growthbook/growthbook/assets/113377031/880e21b5-7343-478c-92b2-21b43843d1a9)

This is the state of the datasources page:

![image](https://github.com/growthbook/growthbook/assets/113377031/3d6f9963-50b3-4a01-a2e7-d0e0d7bf239f)

**Comment by lukesonnet** [comment]
stale
