### ISSUE TITLE
Running component experiments with props in React app

### ISSUE THREAD

**Issue by lightstrike** [growthbook/growthbook#155]
When trying to experiment with Growthbook in a React application (NextJS specifically), I noticed that the only experiment examples show swapping string values. I got a test experiment with no-props components working, but hit an error when trying to use components with props.

Here's what I effectively tried to do:

```jsx
export function PageLayout({ items }) {
  const PCard = useExperiment({
      key: "new-product-card",
      variations: [ProductCard, NewProductCard],
      weights: [0.4, 0.6],
    });

  return (
    <Layout>
      {items.map((item) => (
        <PCard key={item.id} id={item.id} initialState={item} />        
      ))}
    </Layout>
  );
}
```

`ProductCard` and `NewProductCard` take the same props. When trying to compile this page, I hit the following error: `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

Any suggestions on how to fix this or is this use case not currently supported?

**Comment by jdorn** [comment]
`useExperiment` returns an object with a `value` property which will be one of the items in the variations array. I haven't tested this exact use case but if you change the component to `<PCard.value key=...` it should work (at least in theory)

**Comment by lightstrike** [comment]
That makes total sense and that seems to be working like a charm :smile: 

I did the following to keep everything pascal case happy:

```jsx
export function PageLayout({ items }) {
  const PCard = useExperiment({
      key: "new-product-card",
      variations: [ProductCard, NewProductCard],
      weights: [0.4, 0.6],
  });
  const ProductCardVariation = PCard.value; 

  return (
    <Layout>
      {items.map((item) => (
        <ProductCardVariation key={item.id} id={item.id} initialState={item} />        
      ))}
    </Layout>
  );
}
```

Thanks for the quick response! This is a really promising project, keep up the good work. :raised_hands:
