### ISSUE TITLE
Correct Confidence Intervals for Multiple Hypothesis Corrections

### ISSUE THREAD

**Issue by tim06927** [growthbook/growthbook#1567]
# Story

Currently, the confidence intervals (CI) in GrowthBook do not reflect the impact of correcting for multiple hypothesis corrections.  They sometimes contradict the interpretation of the corrected p-values. For example, when controlling the false discovery rate (FDR) with the Benjamini-Hochberg-Procedure (BH), the adjusted p-values can express non-significance, while the confidence intervals express significance. We would like to have correct CI and p-values to not confuse experimenters.

# Detalis

In a [slack-discussion](https://growthbookusers.slack.com/archives/C01T6Q0TEG3/p1689607275256649) in Slack with Luke Sonnet, we found that there is an good-enough way to correct the CI of significant results when controlling the FDR. There are open points regarding CI for non-significant p-values and we did not touch the topic when controlling the familiy-wise error rate (FWER).

**Comment by lukesonnet** [comment]
Thanks for opening this! I do want to fix it, it's just a matter of prioritization right now.

**Comment by jdorn** [comment]
This was fixed in #1740 and released as part of GrowthBook 2.5
