### ISSUE TITLE
[Bug] Memory Leak after upgrading

### ISSUE THREAD

**Issue by RemLampa** [growthbook/growthbook#1615]
### Summary

We're experiencing a memory leak in our NextJS app, and we've managed to narrow down the cause to when we recently upgraded `@growthbook/growthbook-react` (0.9 -> 0.14) to fix the broken Visual Editor.

Just want to sanity check, could either or both of these be causing it?

1. On the client side, we are initializing a new GB instance inside a component, instead of outside of it.
```javascript
const initGrowthbook = (config, ...props) => new GrowthBook({
  clientKey: config.growthbookFeatures.virtualEditorClientKey,
  apiHost: "https://cdn.growthbook.io",
  enableDevMode: process.env.NODE_ENV === "development",
  trackingCallback: (experiment, result) => {
    // some callback func dependent on props
  }
});

// config - NextJS config object
export const GrowthBookWrapper = ({ config, children, ...props }) => {
  const growthbook = useMemo(() => initGrowthbook(config, props), [config, ...props])

  useEffect(() => {
    growthbook.loadFeatures({ autoRefresh: true })
  }, [growthbook])

  useEffect(() => {
    growthbook.setAttributes({
      // some attributes
    })
  }, [growthbook])

  return (
    <GrowthBookProvider growthbook={growthbook}>
      {children}
    </GrowthBookProvider>
  )
}
```
2. On the server side (in `_app.js`' `getIitialProps`), we initialize another GB instance and pass it to the pages.
```javascript
const initializeServerGrowthBook = async ({ req, res, config }) => {
  const growthbook = new GrowthBook({
    apiHost: "https://cdn.growthbook.io",
    clientKey: config.growthbookFeatures.virtualEditorClientKey,
    enableDevMode: process.env.NODE_ENV === "development",
    attributes: {
      // some attributes that rely on req & res
    },
    trackingCallback: (experiment, result) => {
      // callback that needs req & res
    }
  });

  await growthbook.loadFeatures({ autoRefresh: true });

  return growthbook;
}

class _App extends App {
  static async getInitialProps ({ Component, ctx, router, res }) {
      const app = {
        // next config
        config: getConfig(),
      };

     const someProps = {};

      const growthbook = await initializeServerGrowthBook({
        req: ctx.req,
        res: ctx.res,
        config: app.config,
      });

      if (Component.getInitialProps) {
        pageProps = await Component.getInitialProps({
          ...ctx,
          // pass growthbook instance
          growthbook
        })
      }

      return {
        app,
        pageProps: {
          ...pageProps,
          ...someProps
        },
      }
  }

  render () {
    const {
      Component,
      app,
      pageProps,
    } = this.props

    return (
      <GrowthBookWrapper config={ app.config }>
        <Component { ...pageProps } />
      </GrowthBookWrapper>
    );
  }
}
```

Reason we're doing these is we have some configuration dependent on props (client-side) and req/res objects (server-side).
Eager to hear your thoughts. Thanks! 

#### Expected Behavior

NextJS application works without memory leaks.

#### Current Behavior

NextJS is having memory leaks, causing its service to unnecessary autoscale to an absurd number of containers. We temporarily created a scheduler that restarts the service every few hours.

**Comment by jdorn** [comment]
A few changes should stop the memory leak
1. Don't pass `autoRefresh` on the server side instance. This opens a streaming connection and prevents garbage collection from happening.
2. Call `growthbook.destroy()` in getInitialProps after you're done using it. This does further cleanup for garbage collection.
3. On the front end, if the useMemo is changing frequently, you might want to add a useEffect hook to call destroy when the GrowthBook instance changes.

**Comment by jdorn** [comment]
Closing this as solved.  Please create a new issue if this is still a problem
