### ISSUE TITLE
[Bug] TypeScript: Compilation errors in the Growthbook library files

### ISSUE THREAD

**Issue by aminesafi8** [growthbook/growthbook#1636]
**Compilation errors**

`TypeScript error in /XXX/node_modules/@growthbook/growthbook/dist/types/growthbook.d.ts(188,37):
Type expected.  TS1110

    186 | export declare type ApiHost = string;
    187 | export declare type ClientKey = string;
  > 188 | export declare type RepositoryKey = `${ApiHost}||${ClientKey}`;
        |                                     ^
    189 | export declare type LoadFeaturesOptions = {
    190 |     autoRefresh?: boolean;
    191 |     timeout?: number;`

**Expected Behavior**

No compilation errors

**Current Behavior**
The project does not start

<img width="1431" alt="Screenshot 2023-08-31 at 10 58 13" src="https://github.com/growthbook/growthbook/assets/25407983/39352cd1-f1e5-4ab7-be40-2b157197ee9a">
<img width="1083" alt="image" src="https://github.com/growthbook/growthbook/assets/25407983/e2b8ec80-2309-4801-82f8-07a57c37086e">

**Environment Information**

| Name | Version |
|--------|--------|
| node | 14.21.3 |
| npm | 6.14.18 |
| typescript | 3.9.7 | 
| @growthbook/growthbook | 0.27.0 |

**Comment by bryce-fitzsimons** [comment]
This will be patched in an upcoming version of our SDK. Meanwhile if you need to compile and don't mind modifying the source locally, you can change the offending line to:
`export declare type RepositoryKey = string;`

**Comment by aminesafi8** [comment]
@bryce-fitzsimons But in this case I have to do the change in the **node_modules** files.

**Comment by jdorn** [comment]
This should be fixed in the latest SDK release
