### ISSUE TITLE
[Bug] Given the same user attributes, the JS and React SDKs evaluate to different feature values

### ISSUE THREAD

**Issue by bttf** [growthbook/growthbook#1664]
### Summary

We've received multiple reports from users that when setting the same user attributes, the JS SDK and the React SDK will evaluate to different feature values. 

#### Expected Behavior

Given the same user attributes, the evaluated features values should be identical.

#### Current Behavior

Given the same user attributes, the evaluated features between two SDKs do not match. 

#### Repro steps
1. Run the Growthbook Devtools extension against a React app using the React SDK.
2. Make sure you have a running experiment with a boolean feature flag that is hashed on the user ID.
3. Load the app, open DevTools, and manipulate the user ID in-app to flip the feature value.
4. Since the DevTools extensions leverages the JS SDK internally to compute feature values, you will see that the values do not always match the values that are computed in the React app.

## User Reports
1. https://growthbookusers.slack.com/archives/C01T6PKD9C3/p1694101823445679
2. https://growthbookusers.slack.com/archives/C01T6PKD9C3/p1694079049606449

**Comment by aminesafi8** [comment]
The library has a lot of bugs, 255 open issue with no answer, I have already created an issue with the compilation, the library doesn't compile!!!!

[[Bug] TypeScript: Compilation errors in the Growthbook library files](https://github.com/growthbook/growthbook/issues/1636)

**Comment by maksym-plotnikov** [comment]
Using JS SDK with Angular and having the same issue - for the same user id sometimes flag evaluates with different values. Please fix ASAP🙏
