### ISSUE TITLE
[Feature] Non-interactive mode for `growthbook auth login` 

### ISSUE THREAD

**Issue by kevinbarabash** [growthbook/growthbook#1694]
### Description of Feature

I'd like to use `growthbook auth login` as part of a CLI script to generate TypeScript types.  The script will fetch the API key from our key manager and I'd like to be able to pass it as a command line argument to `growthbook auth login`.  Also, it would be nice if this command didn't prompt for a profile name and used `default` in non-interactive mode.

### Related Issues

None

**Comment by tinahollygb** [comment]
For scripts and CI/CD workflows, we recommend you create the `~/.growthbook/config.tml` file manually. You can read how to do that here: https://docs.growthbook.io/tools/cli#usage-on-cicd

In the future, any tickets related to the CLI should be opened in the CLI repository: https://github.com/growthbook/growthbook-cli

Let us know if the documentation related to the CI/CD workflow is not sufficient to solve your problem.
