### ISSUE TITLE
Make metric queries include current date

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#171]
When we show data for a metric, we currently don't include the current day's worth of data.  For users just getting set up, they may only have events from today, and want to test out if the query is working, and by excluding events from 'today', they can't see results.

TODO:
-  [ ] In `packages/back-end/src/services/experiments.ts` on line `329`, instead of using the current date as the value of `to`, use tomorrow instead (add 1 day).

**Comment by phershbe** [comment]
@Auz @jdorn I made a pull request on this even though it's pretty old, I'm self-taught and trying to get experience. Feel free to turn it down if it's not needed anymore.
