### ISSUE TITLE
[Bug] Can't edit SQL when making a new metric

### ISSUE THREAD

**Issue by idau** [growthbook/growthbook#1716]
### Summary

In the process of making a new metric, in step 2 -> Query settings, after pressing the "edit SQL"-button - I am unable to "access" the edit pane. As a result I cannot make a new metric. The same happens if I try to make a copy of an existing metric.

#### Expected Behavior

The possibility to edit the SQL for a metric.

#### Current Behavior

No reaction in the UI when I click the SQL edit pane. I can't see any example SQL nor write/edit.

<img width="943" alt="Screenshot 2023-10-06 at 16 47 16" src="https://github.com/growthbook/growthbook/assets/22680099/a1551f3e-99ee-47f8-91c1-c4ad16802ce6">

**Comment by mknowlton89** [comment]
Hey, @idau - Are you still experiencing this? I'm having trouble reproducing it.

If you are still experiencing it, can you tell me what type of Data Source the metric you're trying to connect is connected to?

**Comment by idau** [comment]
No, it no longer was an issue the day after I reported it.
