### ISSUE TITLE
[Bug] The total in summary popup shows percentage for number of conversions

### ISSUE THREAD

**Issue by linusbrimstedtellos** [growthbook/growthbook#1722]
### Summary

The total in summary popup shows percentage for number of conversions

#### Expected Behavior

It should just show the actual number

#### Current Behavior

We have conversions set up as a metric.

In the popup showing stats about the metric, it shows  17484 conversions as 1748400%.

<img width="450" alt="image" src="https://github.com/growthbook/growthbook/assets/123365931/3e96bfe6-cdec-4d59-a137-396b56c0269d">

I think this happened with a recent update to your saas offering.

**Comment by PrashantIndurkar** [comment]
Hi,
So you mean it should only show 1,748,400  without percentage(%) sign. only number in the Total right?

**Comment by PrashantIndurkar** [comment]
Hi @linusbrimstedtellos ,
So you mean it should only show 1,748,400 without percentage(%) sign. only number in the Total right?

**Comment by linusbrimstedtellos** [comment]
Hi, i think it should who 17484, i.e. there are two zeroes too many and a percentage sign.

**Comment by linusbrimstedtellos** [comment]
Maybe this screenshot makes it a bit more clear:
![image](https://github.com/growthbook/growthbook/assets/123365931/d5778e79-6893-4397-b907-0a5c6a86dd43)

**Comment by lukesonnet** [comment]
Thanks for reporting this. We're looking in to it.
