### ISSUE TITLE
[Bug] Remove Billing page for Enterprise customers

### ISSUE THREAD

**Issue by august-growthbook** [growthbook/growthbook#1738]
### Summary
- Enterprise customers should not see a Billing page
- Plan type discrepancy shown for users on an Enterprise contract
- [Slack convo in internal Slack workspace](https://growthbookapp.slack.com/archives/C046L8DQD6F/p1697041328137659)
- @jdorn believes the code is looking for the `disableSelfServeBilling` flag right now and it should also look for the `enterprise`  flag.

#### Expected Behavior
Enterprise users should have the Billing page disabled in the GrowthBook Dashboard since all account-related matters are managed through their Account Executive.

#### Current Behavior
- At least 1 Enterprise customer is seeing a Billing page in their Dashboard (this page should be invisible to users on an Enterprise plan since they have an Account Executive who manages these things)
- This same customer also sees a discrepancy between plan types (Free and Enterprise) in different parts of the Dashboard (see screenshots below)

![image (7)](https://github.com/growthbook/growthbook/assets
![image (8)](https://github.com/growthbook/growthbook/assets/144278508/1f2792ce-9d1f-4bc3-86c6-056c2cdb30cd)
/144278508/8800559a-1495-47ad-b2e7-74c8967a1f60)

**Comment by mknowlton89** [comment]
Closing this issue - this will be resolved via the closing of Issue [#1747](https://github.com/growthbook/growthbook/issues/1747) which will be closed by PR [1760](https://github.com/growthbook/growthbook/pull/1760)
