### ISSUE TITLE
[Bug] On Experiments, when editing Targeting Conditions, the previously saved conditions are removed

### ISSUE THREAD

**Issue by a4averma** [growthbook/growthbook#1742]
### Summary
For an experiment, I intended to adjust the split to 50/50, but the targeting condition was deleted.

#### Expected Behavior
Clicking the edit button should launch the edit modal and preserve previous conditions.

#### Current Behavior
All targeting conditions were erased and a 50/50 split was applied without any specific conditions.

https://github.com/growthbook/growthbook/assets/1889638/51980fef-97da-4d56-9746-6e3cab4cf517

**Comment by bryce-fitzsimons** [comment]
From the video it looks like you may be using an older build. I believe this issue is patched in the latest version of GrowthBook. Feel free to open a new issue if this is not the case.

**Comment by praveen-quizizz** [comment]
@bryce-fitzsimons can you please point me to the bug that caused this and the commit or version that fixed it.
The current UI is a revamp and I am a little skeptical of bumping up the version all together.
