### ISSUE TITLE
[Bug] Expired License Keys Cause API Error State

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#1774]
When a user adds an enterprise or pro key through the GrowthBook UI, and then that key expires, the API will throw an error about the expired license and not run. This means users cannot access the UI to delete the expired license key.

**Comment by newb1e** [comment]
I have encountered a similar but even weirder bug. We did have some license which expired Oct 31st. 
We get a message about "Your License Key trial expired on 2023-10-31", though we're not using this key anymore. 
Upgrading to version 2.4.0 works well. Upgrade to version 2.5.0 locks me out the UI with this message.

**Comment by newb1e** [comment]
As a workaround for my issues I had to connect to the Mongodb. After connecting to the mongodb server and appropriate db (organizations) was able to run:
```db.organizations.updateOne( { _id: ObjectId("obj_id") }, { $set: { licenseKey: '' } } )```

**Comment by smrdotgg** [comment]
I've replicated and fixed the bug, but the code change occurred in the `enterprise` package. 

Should I make a PR anyway? @Auz
