### ISSUE TITLE
[Bug] Docker Hub tagged versions don't have arm64 images

### ISSUE THREAD

**Issue by cpmsmith** [growthbook/growthbook#1819]
### Summary
On the official Docker Hub page, while the per-commit images have both amd64 and arm64 (e.g. [`git-5026b26`, currently the latest](https://hub.docker.com/layers/growthbook/growthbook/git-5026b26/images/sha256-ae24e57d53797c776a5bc7030f27c63cf86642c085b1d71de2460168025b2eb3?context=explore)), the tagged releases (e.g. [`2.5.0`](https://hub.docker.com/layers/growthbook/growthbook/2.5.0/images/sha256-f5ef6d2130c33c99d0dacb03b461bed6e31acfc187346518b30b6c1a2698d660?context=explore)) only have amd64.

#### Expected Behavior

The tagged release versions should have amd64 and arm64 images.

#### Current Behavior

The tagged release only has an amd64 image.

#### Search Keywords
aarch64, x86_64, x64, linux/amd64

**Comment by jdorn** [comment]
This should be fixed now
