### ISSUE TITLE
Power Calculator to estimate experiment impact / running time before starting

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#184]

**Comment by tim06927** [comment]
We are currently looking into enabling our users to do better power calculations. As they got used to GrowthBook as their to go place for experimentation and we have all metrics implemented in GrowthBook it would be wonderful if that would be included in the tool. Can you let us know if this is still on some roadmap? Happy to through our custom dev time behind this issue.

**Comment by lukesonnet** [comment]
Closing this as power is available in Alpha in the app and future improvements have their own issue tracker right now (e.g. #2716 ) and roadmapped items like using existing traffic/metric data to populate some fields.
