### ISSUE TITLE
[Bug] Publishing a feature is blocked

### ISSUE THREAD

**Issue by mohammedyasir** [growthbook/growthbook#1857]
### Summary

A non admin GB user is unable to publish to env which they have access to and sometimes they are able to publish to env they do not have access to.

I have reproducible steps for former case, for latter case I do not have steps to reproduce it occurs randomly.
Please refer the below recording for the steps:

https://github.com/growthbook/growthbook/assets/26865401/7c5f3a3d-cd6f-4257-825e-ab9f1da0188e

Once I am in this state, I am unable to get out of this almost like a day, even if try reloading the page, logout/login, try in incognito, refer below screenrecording.

https://github.com/growthbook/growthbook/assets/26865401/bf255b96-4e0b-4f6c-804c-950b79c7f62b

Left side user is collaborator and has engineer access in 2 environments (dev_sandbox, pre_prod) and he does not have access to customer_prod. Refer the screenshot below. And right side user in admin.

![Screenshot 2023-11-16 at 8 16 04 PM](https://github.com/growthbook/growthbook/assets/26865401/22110d6a-d088-4d45-83ac-7c5bc4bd3823)

#### Expected Behavior

If the user has permission to publish in a environment, he should not be blocked from publishing.

#### Current Behavior

The user who has permission to publish in a environment is being blocked from publishing.

**Comment by august-growthbook** [comment]
Hi Mohammed, thanks for raising this! I believe at least part of the issue is also addressed here:
https://github.com/growthbook/growthbook/issues/1684

**Comment by jdorn** [comment]
Thanks for all the detailed info.  I think I discovered the bug and am working on a fix now
