### ISSUE TITLE
[Bug] Query fails in GrowthBook but not Athena

### ISSUE THREAD

**Issue by tim06927** [growthbook/growthbook#1866]
### Summary

Occasionally (maybe 1 in 25 queries), queries fail in our self hosted version of GrowthBook (2.5.0) that relies on AWS Athena for querying.

![Image](https://github.com/growthbook/growthbook/assets/25033213/aae5d8b5-4080-43b1-85e0-b2ae000a8c1b)

#### Expected Behavior

As long as Athena, the underlying query engine returns queries successfully, these should arrive in GrowthBook. Otherwise the error message could be more descriptive to let us know what failed.

#### Current Behavior

Queries that GrowthBook sends to Athena fail with errors similar to the one in the screenshot. When we check the Athena log, the query was completed and the result is accessible. On the next try the query usually succeeds. On top of the missing results, as Athena executes the queries successfully this generates querying cost.

**Please use our custom dev time to work on this issue.**

**Comment by jdorn** [comment]
Thanks. That's helpful.  I can definitely add some logic to look for the `SlowDown` string in the error message and wait a little longer to see if it transitions back to queued/running.

**Comment by fabianmarinog** [comment]
Hi @jdorn yes, please add this logic, do you have an estimated timeline for this to be available?
