### ISSUE TITLE
[Feature] Add a date and time to the "Test feature rules"

### ISSUE THREAD

**Issue by tim06927** [growthbook/growthbook#1878]
### Description of Feature

We love the "Test feature rule" function in GrowthBook. However, we often use scheduling to release features, especially for marketing. Currently, it is not possible to test the future behavior of a feature with "Test feature rule". It would be great if it would be possible to set the data and time in the simulation.

**Please use our custom dev time to work on this issue.**

**Comment by fabianmarinog** [comment]
It would also be great to be able to test rules that are marked as draft. Sometimes there's an experiment running and we want to test a new rule but it is not possible without affecting the one that is running.

**Comment by Auz** [comment]
By default, the tester works with draft rules- should we make that more clear?
