### ISSUE TITLE
[Bug] Conversion Delay settings for Fact Tables Metrics working incorrectly

### ISSUE THREAD

**Issue by ndubitsk** [growthbook/growthbook#1882]
### Summary

When we calculate the result of an experiment with exposed Start/End date, and add an activation metric, the query for the activation metric is incorrect – for the activation metric query collects data for one day more (for example `End Date = '2023-11-01 11:00:00'`, for activation metric query will be filtered as `'BETWEEN 2023-10-15 00:00:00 AND 2023-11-02 11:00:00'`)

This can be fixed by setting up `Conversion Delay (hours) = - 24`.

#### Expected Behavior

We expect the End Date for the activation metric to be the same as for other metrics and results configuration.

#### Current Behavior

The end Date for the activation metric is one day more by default, with Conversion Delay (hours) set to 0.

**Comment by lukesonnet** [comment]
Thanks for the report...

Two questions:

* Can you share the full query where this filtering is happening? or at least the `__activationMetric` CTE and the `__experimentUnits` CTE?
* What is your desired conversion window for the activation metric? Did you set a conversion window for it?

**Comment by ndubitsk** [comment]
There is a cte `__activationMetric`

```
        , __activationMetric AS (-- Metric (cr2view_recs_MAIN [a])
    SELECT account_id  AS account_id,
           1           AS value,
           m.timestamp AS timestamp
    FROM (
             SELECT session_started_at AS timestamp
                  , account_id
                  , session_id
                  , widget_space_name
                  , widget_section_name
                  , widget_section_id

             FROM marts.xxxx

             WHERE session_started_at BETWEEN '2023-11-06 09:04:00' AND '2023-11-22 13:45:00'
               AND account_id != 0

             GROUP BY timestamp, account_id, session_id, widget_space_name, widget_section_name, widget_section_id
             ) m

    WHERE m.timestamp >= toDateTime('2023-11-06 09:04:00', 'UTC')
      AND m.timestamp <= toDateTime('2023-11-22 13:45:00', 'UTC')
)
```

And there is `__experimentUnits` cte:
```
        , __experimentUnits AS (
    -- One row per user
    SELECT e.account_id                                                          AS account_id
         , if(count(DISTINCT e.variation) > 1, '__multiple__', max(e.variation)) AS variation
         , MIN(e.timestamp)                                                      AS first_exposure_timestamp
         , MIN(if(a.timestamp >= e.timestamp, a.timestamp, NULL))                AS first_activation_timestamp

    FROM __experimentExposures e


             LEFT JOIN __activationMetric a ON (a.account_id = e.account_id)

    GROUP BY e.account_id
)
```


> What is your desired conversion window for the activation metric? Did you set a conversion window for it?
We wanted to use this metric without conversion window. And we didn't set any conversion window for the metric.

**Comment by lukesonnet** [comment]
Ok. To my eyes this is just some unnecessary data retrieval in the first CTE, but we still should be doing the right filtering in the `__distinctUnits` CTE. 

My PR above #1922 fixes this unnecessary data retrieval. 

That said, until that lands, I would recommend you undo your change of adding `Conversion Delay (hours) = - 24`. This could actually cause inaccuracies if people are able to activate before the exposure. So I advise you revert this even before my PR above lands (which will fix the issue you point out, which is simply one of retrieving data that we later discard with a WHERE clause).
