### ISSUE TITLE
[Bug] The "value" condition in a Metric's WHERE clause isn't needed for binomial metrics

### ISSUE THREAD

**Issue by august-growthbook** [growthbook/growthbook#1970]
### Summary

When adding a new metric **and selecting "binomial" as the metric type**, the default query assumes that there is a key called `value` in `event_params` . This is not always the case. When this key is not present with the event/metric the query/queries will throw an error. 

![d3513bcb-7afb-42f4-b678-360c097078cc](https://github.com/growthbook/growthbook/assets/144278508/76950ade-cbba-4703-bfcb-7599d7cbb911)

#### Expected Behavior
The "value" shouldn't be needed at all for a binomial metric.

**Comment by ptdatta** [comment]
Hey @august-growthbook Can I give it a try?

**Comment by august-growthbook** [comment]
Sure, please do!

**Comment by lukesonnet** [comment]
This was closed by #2216
