### ISSUE TITLE
[Feature] Runtime Saved Groups: Disallow non-string values in $groups array

### ISSUE THREAD

**Issue by august-growthbook** [growthbook/growthbook#1972]
### Description of Feature

Since only string values are allowed in the `$groups` array that represents a Group Identifiers, we should block the ability to add non-string values as an attribute when creating Runtime Saved Groups.

[Docs](https://docs.growthbook.io/features/targeting#runtime-saved-groups:~:text=You%20need%20to%20include%20a%20special%20attribute%20in%20your%20integration%20named%20%24groups%20that%20contains%20an%20array%20of%20these%20identifiers%20as%20strings.)

**Comment by jdorn** [comment]
Not relevant anymore with the release of Condition Groups
