### ISSUE TITLE
[Feature] Exposure model as a dimension/dropdown option

### ISSUE THREAD

**Issue by tim06927** [growthbook/growthbook#1999]
### Description of Feature

For some experiments both exposure models - experiment duration and first exposure - can generate valuable insights. Therefore it would be nice to be able to put the two models side-by-side, comparable to the dimension drop-down in the experiment result view. FYI @qiongwu-git

**Comment by lukesonnet** [comment]
I think it's more likely we support a variety of time series analyses which help you understand how effects change as you roll up more days after exposure. E.g. a graph that shows Effect for all users 1 day after exposure, 2 days after exposures, and so on.

Would that fit your needs here?

**Comment by lukesonnet** [comment]
One other solution is to keep the First Exposure model in effect but use a Fact Metric where you can turn conversion windows off altogether to create two versions of a metric, one with and one without a conversion window.

**Comment by qiongwu-git** [comment]
Hi @lukesonnet, thanks for your suggestions! With the second proposal, if I'm monitoring 10 metrics (with conversion windows) for one experiment, does it mean that I need to create 10 more (without conversion windows)?

**Comment by lukesonnet** [comment]
Unfortunately yes, that is what you'd need to do. We're considering making these kinds of "metric variants" easy to create, manage, and add to an experiment, and we're also actively working on the time series views.

**Comment by tim06927** [comment]
I see the point and will therefore close this issue.
