### ISSUE TITLE
Show overall business impact for an experiment

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#210]
We have all the info we need to calculate the overall business impact for each variation/metric in an experiment.

```
p = percent of traffic in experiment (coverage)
t = traffic allocation for the variation
u = relative uplift
b = baseline per-user value
n = number of users in variation
d = number of days the phase has been running

impact _per_year = u * b * n *  (1/p) * (1/t) * (365/d)
```

Breaking out the different parts, `u * b * n` is the total incremental value added by the variation during the experiment.  Multiplying by `(1/p) * (1/t)` shows what the impact would have been if the variation was rolled out to 100% of all users during the time the test was running.  Multiplying by `365/d` coverts it to an annual impact, regardless of how long the test was running for.

As an example, if an experiment is running for 40% of traffic over 14 days, with a 50/50 split, and the variation had 1000 users with a baseline mean of $5 and a 10% uplift, the overall impact would be `(0.1)*(5)*(1000)*(1/0.4)*(1/0.5)*(365/14)`= `$65,178/year`

For each variation, we can add a new column in the table for "Est. Annual Impact" that shows the result of these calculations.

This doesn't really make sense for most duration metrics, but maybe it doesn't hurt to include it anyway.  It's still useful for comparing the impact across experiments.

**Comment by lukesonnet** [comment]
This has been implemented as Daily Scaled Impact and is closed by #1766. See the docs: https://docs.growthbook.io/app/experiment-results#difference-types.
