### ISSUE TITLE
Not possible to see "Features" within a "Project"

### ISSUE THREAD

**Issue by andehen** [growthbook/growthbook#213]
It is possible to add a "Feature" while a "Project" is active. But when viewing "Features" and a project is active, you can not get past the "Setup steps" [0]. To view the feature, you have to select "All projects".

[0]
![image](https://user-images.githubusercontent.com/754494/149359183-1d41a74b-e3fc-4939-b5c2-44cd23f1686f.png)

**Comment by jdorn** [comment]
Thanks for catching this.  Just pushed a fix, should be live in about 10 minutes
