### ISSUE TITLE
[Bug] Roles are intertwined in the creation of Experiment Rules

### ISSUE THREAD

**Issue by tim06927** [growthbook/growthbook#2131]
### Summary

Both engineers (responsible for features) and analysts (responsible for experiments) cannot set up "Experiment Rules" from a feature. This is only possible for the experimenter role.

#### Expected Behavior

As experiment rules are a property of a feature, an engineer role should be allowed to set up a new experiment rule, even though, this means creating an experiment.

#### Current Behavior

We need to give too many privileges (experimenter role) to engineers, such that they are able to set up features with rules.

**Comment by Natalienoiman** [comment]
This now has a high priority

**Comment by fabianmarinog** [comment]
@lukesonnet  I see this was implemented in https://github.com/growthbook/growthbook/pull/2537 ?

**Comment by Kevin-Chant** [comment]
Hi @tim06927, I'm looking into this and see two main options with our current permissions behavior. Can you let me know if these are sufficient for your use-case?

1. Create a custom role for engineers with all the current Engineer policies + `ExperimentsFullAccess`. This would let engineers create experiment rules but continue to restrict things like datasource configuration.
2. Have other users create experiments beforehand, and have engineers only be responsible for using existing experiments in their experiment rules. The Engineer role does currently allow for creating experiment rules if the experiment being referenced already exists. This seems to better represent your desired behavior in terms of permissions, but as creating an experiment is also a rather privileged action it will require either the Experimenter role or a custom role with a combination of Engineer and Analyst permissions.

**Comment by lukesonnet** [comment]
Hi! Marking this as closed due to the PR Kevin merged above which  I think addresses the original concern.
