### ISSUE TITLE
Wrong in the documentation?

### ISSUE THREAD

**Issue by HenrikHallatorp** [growthbook/growthbook#2177]
### Summary

Is the documentation here correct?
https://docs.growthbook.io/app/metrics

See sceendump, is the text "None - The simplest. Use all data available. " correct? The graph above visualise that this option used limited part of the data?!

#### Current Behavior
![Screenshot 2024-02-29 at 16 27 10](https://github.com/growthbook/growthbook/assets/151713344/1e47198a-f988-4fad-aeba-078a64f9ccf3)

**Comment by lukesonnet** [comment]
Hey Henrik! Another user just pointed this out this morning and it should be fixed now (Fixed by #2181 ).

Sorry for the confusion and thanks for the report.
