### ISSUE TITLE
[Feature] Add possibility to set timeout for Data Source connections (Clickhouse)

### ISSUE THREAD

**Issue by ndubitsk** [growthbook/growthbook#2231]
### Description of Feature

Some of our queries are heavy and they can't get through 60 seconds limit (that is set by default in Clickhouse connection).
We get "504: 504 Gateway Time-out" when we calculate results of an experiment or adding new Fact Table.

We would like to have a possibility to change this setting in Data Sources -> Connection Info

<img width="1385" alt="Screenshot 2024-03-15 at 14 19 59" src="https://github.com/growthbook/growthbook/assets/79838299/a79f31f7-fd13-4166-8a97-9446aa1ee0f6">

**Comment by lukesonnet** [comment]
Hi @ndubitsk . I think this is included as of #2236. Closing this but feel free to re-open if it isn't working for you.

**Comment by ndubitsk** [comment]
@lukesonnet Hey!

Thank a lot!
Looks like this feature works totally fine for queries, that are run in the analytics section.
But new limits seems like doesn't work when we are trying to update SQL query of a Fact Table.

Shall I open a new Feature or a Bug request for this issue?

**Comment by ndubitsk** [comment]
@lukesonnet 
Actually, I just checked and we are getting the Timeout error but query was running only for ~1 minute.
We are expecting that query can run up until 10 minutes as I understand.

<img width="812" alt="Screenshot 2024-03-26 at 10 53 17" src="https://github.com/growthbook/growthbook/assets/79838299/a8177262-2472-4
<img width="1387" alt="Screenshot 2024-03-26 at 10 55 42" src="https://github.com/growthbook/growthbook/assets/79838299/39685807-a67b-47cd-b98b-8a4352ef8ab1">
dfe-a765-bf5b3b61bfea">

**Comment by lukesonnet** [comment]
Long internal thread, but it seems like the main culprit here is a load balancer on the experimenter's Clickhouse infrastructure timing out the request.
