### ISSUE TITLE
Cannot connect to documentdb AWS 

### ISSUE THREAD

**Issue by arka-elocal** [growthbook/growthbook#2260]
{"level":40,"time":1711064871872,"pid":61,"hostname":"ip-x.x.x.x.ec2.internal","err":{"type":"MongooseError","message":"MongoDB prohibits index creation on connections that read from non-primary replicas. Connections that set \"readPreference\" to \"secondary\" or \"secondaryPreferred\" may not opt-in to the following connection options: autoCreate, autoIndex","stack":"MongooseError: MongoDB prohibits index creation on connections that read from non-primary replicas. Connections that set \"readPreference\" to \"secondary\" or \"secondaryPreferred\" may not opt-in to the following connection options: autoCreate, autoIndex\n at throwReadPreferenceError (/usr/local/src/app/node_modules/mongoose/lib/helpers/processConnectionOptions.js:56:9)\n at resolveOptsConflicts (/usr/local/src/app/node_modules/mongoose/lib/helpers/processConnectionOptions.js:22:5)\n at processConnectionOptions (/usr/local/src/app/node_modules/mongoose/lib/helpers/processConnectionOptions.js:13:7)\n at Connection.openUri (/usr/local/src/app/node_modules/mongoose/lib/connection.js:741:13)\n at /usr/local/src/app/node_modules/mongoose/lib/index.js:414:10\n at /usr/local/src/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5\n at Promise._execute (/usr/local/src/app/node_modules/bluebird/js/release/debuggability.js:384:9)\n at Promise._resolveFromExecutor (/usr/local/src/app/node_modules/bluebird/js/release/promise.js:518:18)\n at new Promise (/usr/local/src/app/node_modules/bluebird/js/release/promise.js:103:10)\n at promiseOrCallback (/usr/local/src/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)\n at Mongoose._promiseOrCallback (/usr/local/src/app/node_modules/mongoose/lib/index.js:1288:10)\n at Mongoose.connect (/usr/local/src/app/node_modules/mongoose/lib/index.js:413:20)\n at /usr/local/src/app/packages/back-end/dist/init/mongo.js:34:34\n at Generator.next (<anonymous>)\n at /usr/local/src/app/packages/back-end/dist/init/mongo.js:8:71\n at new Promise (<anonymous>)"},"msg":"Failed to connect to MongoDB. Retrying with field remapping for mongodb v3 to v4"}

Can someone point me to the right  config?

here is my connection string:

mongodb://docdb:mypassword@docdb-x.x.x.x-16-07.cluster-xxxxx.us-east-1.docdb.amazonaws.com:27017/?tlsinsecure=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false" --type "SecureString"

**Comment by Auz** [comment]
It looks like you're not connecting to the primary of the replica set? We know GrowthBook works fine with DocumentDB.
