### ISSUE TITLE
Mixpanel data source doesn't allow region (EU) selection

### ISSUE THREAD

**Issue by billinghamj** [growthbook/growthbook#227]
Hi :)

We're trying to use GrowthBook with Mixpanel, but we have an EU-based project.

When using the Mixpanel API with different regions, you just have to switch the hostname. Rather than `mixpanel.com/api`, it's `eu.mixpanel.com/api`.

Mixpanel document this here: https://developer.mixpanel.com/reference/overview#query-api

It looks like this would get switched here: https://github.com/growthbook/growthbook/blob/58348557cf8e6f429527636908a305074a33e200/packages/back-end/src/services/mixpanel.ts#L57

Maybe by adding a bool or "Standard"/"EU" option to `MixpanelConnectionParams` and `MixpanelForm`?

Thanks!

**Comment by jdorn** [comment]
Just added an option to customize the Mixpanel server.  Takes about 10 minutes for the build process to finish

**Comment by billinghamj** [comment]
@jdorn Thank you! Seems to be working great :)
