### ISSUE TITLE
Schedule Update on an experiment

### ISSUE THREAD

**Issue by HenrikHallatorp** [growthbook/growthbook#2301]
### Description of Feature

We run a lot of experiments and each morning we like to update the data, which in some cases takes a lot of time of each experiment and then needs to be done on all the experiments. 

So to get a more smooth process; could we get a feature to set a schedule on an experiment so that it will update the data on a specific time each day?

Could be done as an option on the three dots menu next to the "Update" button. 

### Related Issues

None
![Screenshot 2024-03-28 at 14 26 50](https://github.com/growthbook/growthbook/assets/151713344/d7dad54c-82d2-4049-8196-b7002764f416)

**Comment by august-growthbook** [comment]
Hi Henrik 👋🏻 It is actually already possible to schedule experiment updates!

In the left navigation bar, go to Settings > General > Experiment Settings, as shown here:

<img width="1186" alt="Screen Shot 2024-03-29 at 10 20 06 AM" src="https://github.com/growthbook/growthbook/assets/144278508/894bec1a-220c-4470-a611-a74852b6c1ee">
