### ISSUE TITLE
[Question] Return only the features flags of an app

### ISSUE THREAD

**Issue by KevinToala** [growthbook/growthbook#2432]
Hi 👋

In our company we have different applications for clients, for stores, backoffice, etc...
Is there a way with growthbook that when obtaining the features flag in each app it only returns the features flag corresponding to that app?
We are seeing that all the apps currently return all the features flags in the response json (we use the growthbook js sdk) and it generates noise for us to obtain the features flag of the backoffice app in the client app.
Maybe you can but you don't find much information in the documentation. Could you help me with this question?

Thanks

**Comment by jdorn** [comment]
Hi. We have the concept of Projects. You can configure projects under settings. Then, assign each feature to a project. Finally, create a new SDK connection for each project. Each SDK connection will have its own clientKey you reference in the SDK and it will only return features that are part of that project.
