### ISSUE TITLE
Python error - probability of being negative is higher than 0.0001

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#246]
Some inputs for gaussian metrics cause a Python warning:

> RuntimeWarning: probability of being negative is higher than 0.0001 (=0.1607914128899579). log approximation is in-exact

Python code to reproduce:

```python
from gbstats.bayesian.main import gaussian_ab_test

gaussian_ab_test(
  m_a = 0.26,
  s_a = 5.12,
  n_a = 381,
  m_b = 0.84,
  s_b = 12.26,
  n_b = 24145
)
```

The line within `gaussian_ab_test` which is causing the warning:
```python
from gbstats.bayesian.dists import Norm

Norm.moments(0.26, 0.2623055460242226, log=True)
```

And the code within `Norm.moments` that is triggering it:
```python
max_prob = np.max(norm.cdf(0, 0.26, 0.2623055460242226))
if max_prob > EPSILON:
    warn(
        f"probability of being negative is higher than {EPSILON} (={max_prob}). "
        f"log approximation is in-exact",
        RuntimeWarning,
    )
```

A couple options for fixing this:
1. Suppress the runtime warning and use the in-exact approximations
2. Detect this condition at the top of `gaussian_ab_test` and return immediately with zeros for uplift, risk, etc. (like we do when stddev = 0)
3. Figure out alternate way to calculate results when log approximation is in-exact

**Comment by nate-one-1978** [comment]
Titans

**Comment by nate-one-1978** [comment]
💘
