### ISSUE TITLE
[Bug] Users with global no-access role are unable to view their personal access tokens

### ISSUE THREAD

**Issue by mknowlton89** [growthbook/growthbook#2474]
### Summary

If a user has a global `noaccess` role, we are not returning any of their personal access tokens when landing on `/account/personal-access-tokens` and it feels like they should be able to view them, considering they could have other project-based roles.

#### Expected Behavior

When visiting `/account/personal-access-tokens` users with global `noaccess` role should see their personal access tokens.

#### Current Behavior

Currently today, the user gets an empty state message and has a cta to create a personal access token, but once created, it never renders on the page because the no access filter is filtering them out.

**Comment by akash-ind** [comment]
Hey @mknowlton89, Can you please assign me this bug?
