### ISSUE TITLE
[Bug] Global Webhooks do not report all possible SDK payload changes

### ISSUE THREAD

**Issue by dlemaigl** [growthbook/growthbook#2525]
### Summary

The Global Playbooks documentation states that the webhook is triggered when the SDK payload changes, but there are some cases where this is not the case, like when the user changes the SDK to be encrypted. Creations and deletions are also not notified.

#### Expected Behavior

All operations that change, create, or delete SDKs in any way should be notified

#### Current Behavior

Only a subset of operations like feature flag changes are notified.

**Comment by jdorn** [comment]
Yes, this should have been fixed by this line in the PR: https://github.com/growthbook/growthbook/pull/2533/files#diff-f309a8a4f4821ef9e4a16b37dd6bbdf990b6eed36cd436bff2605ada341a20ecR76

If the bug is still happening, can you include steps to reproduce along with the build version/date you are running?

**Comment by dlemaigl** [comment]
Hi @jdorn,

I am testing version a502b5d, the last one from today. The steps to reproduce the bug are the following:

1. Create a FF
2. Create an SDK. The Global webhook will not be triggered
3. Change the value of the FF, The GW will be triggered
4. Delete the SDK. The Global webhook will not be triggered

![steps](https://github.com/growthbook/growthbook/assets/779802/fcd39f36-34f8-4d86-aa8f-36ec41b3e35e)

**Comment by august-growthbook** [comment]
@dlemaigl We just merged a fix for this: https://github.com/growthbook/growthbook/pull/2592

Please let me know if you are still seeing any issues.

**Comment by dlemaigl** [comment]
@august-growthbook, now it triggers correctly on create SDK but when deleting the SDK it does not trigger it
