### ISSUE TITLE
Broken link to the white paper

### ISSUE THREAD

**Issue by vanbrands** [growthbook/growthbook#255]
The link to the white paper in the `statistics` sections of the docs is leading to a 404 page. Was it moved to another place?  

https://github.com/growthbook/growthbook/blob/main/packages/docs/pages/statistics.mdx#growthbooks-statistics

![image](https://user-images.githubusercontent.com/36680823/153419700-c47b46e5-5c98-410e-bae4-44cd3c855556.png)

Thanks!!

**Comment by jdorn** [comment]
Thanks for finding that.  We just updated our website yesterday and forgot to update that link.

The new location of the PDF is at https://docs.growthbook.io/GrowthBookStatsEngine.pdf

**Comment by vanbrands** [comment]
Awesome @jdorn , thanks for the quick fix!! 👊🏼 
By the way, I found the same link in the footer of home page as well (`Statistics details`).

![image](https://user-images.githubusercontent.com/36680823/153421693-596b46d5-66d1-4e55-a71c-657489717551.png)

**Comment by jdorn** [comment]
Thanks, just fixed that link too.
