### ISSUE TITLE
[Bug] Test not splitting traffic correctly after reset and re-randomizing audience

### ISSUE THREAD

**Issue by khickson** [growthbook/growthbook#2556]
### Summary
Experiment Key: bff-adr-donation-form-redesign-v2
had an issue where a developer started a experiment but didn't have it linked to the correct bigquery instace, after test launch he changed this but didn't restart and re-randomize the audience. We caught this a week later after noticing the control was receiving a lot higher traffic (almost 100 more users) than the variant. I had the dev restart the experiment and re-randomize the audience and traffic looked correct at first but now we are noticing again the control receiving a significant amount more of an audience than the variant.

#### Expected Behavior

traffic should be split 50/50

#### Current Behavior

traffic seems to favor the control more even have restarting and re-randomizing the audience.

Phase 1:
![image](https://github.com/growthbook/growthbook/assets/39208278/a463eeeb-3154-4cfa-9578-cf40033566aa)
![image](https://github.com/growthbook/growthbook/assets/39208278/6009ffb0-9053-4692-8b9a-8f1ac95152fb)

Phase 2:
![image](https://github.com/growthbook/growthbook/assets/39208278/17228293-cdfb-49a1-a5c0-209cc0a21de5)

**Comment by lukesonnet** [comment]
Please feel free to raise this question in our User Slack. However, your issue probably boils down to one of the issues outlined here: https://docs.growthbook.io/kb/experiments/troubleshooting-experiments#problem-2-srm-errors-traffic-imbalance-in-the-experiment
