### ISSUE TITLE
[Feature] Autoupdate metrics on schedule

### ISSUE THREAD

**Issue by sshleifer** [growthbook/growthbook#2572]
### Description of Feature

<img width="475" alt="image" src="https://github.com/growthbook/growthbook/assets/6045025/98a8980e-0164-4907-8a4f-2aafdd8f1850">

This button takes like 15 minutes to compute new metrics.
Would it be possible to run it on a schedule so that I dont need to navigate, click, context switch, and come back to see results?
Apologies if already possible and I just dont know how!

**Comment by lukesonnet** [comment]
Hey, this is doable. Go to your organization settings and you can go down to the Experiment Settings and set up auto-updates.

<img width="1035" alt="Screenshot 2024-06-05 at 9 17 29 AM" src="https://github.com/growthbook/growthbook/assets/5298599/96569cba-6be0-4b38-ab45-fa4c76f7ce4f">
