### ISSUE TITLE
[Bug] CORS issue when firsttime signup

### ISSUE THREAD

**Issue by llmiell** [growthbook/growthbook#2573]
### Summary
 i’m trying to get setup with self hosted growthbook on kubernetes. im running into CORS issues during /auth/firsttime request from growthbook web to growthbook api. i’ve set the appropriate env vars such as APP_ORIGIN to the backend api server and API_HOST to frontend service. using openresty for ingress but im still getting blocked on the username / password auth form page.

**Setting on openresty for growthbook-api**

```
location ~ / {
        # CORS headers
        add_header 'Access-Control-Allow-Origin' $growthbook-ui  always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
        add_header 'Cache-Control' 'private, no-cache, no-store, max-age=0, must-revalidate';
        add_header Content-Security-Policy   "default-src 'self' http: https: 'unsafe-eval' data: blob: 'unsafe-inline'; connect-src *; object-src 'none';" always;


        # if preflight request, we will cache it
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' $growthbook-ui always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
            add_header 'Cache-Control' 'private, no-cache, no-store, max-age=0, must-revalidate';
            add_header Content-Security-Policy   "default-src 'self' http: https: 'unsafe-eval' data: blob: 'unsafe-inline'; connect-src *; object-src 'none';" always;

            # Extension
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' '*';
            add_header 'Content-Length' 0;
            return 204;
        }
```

#### Expected Behavior

Login Success on firsttime

#### Current Behavior
`Access to fetch at '<https://growthbook-api><DOMAIN>/auth/firsttime' from origin '<https://growthbook-ui>.<DOMAIN>' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`

![image](https://github.com/growthbook/growthbook/assets/18067068/e2502851-db2c-4acc-b8e8-48d1cc440d70)

**Comment by jainabhishek14** [comment]
@llmiell What was the issue. I am also getting the same. I have allowed * in `Access-Control-Allow-Headers` still it is asking me to add content-type in that header?
