### ISSUE TITLE
Not possible to add Google Analytics

### ISSUE THREAD

**Issue by Fr3di** [growthbook/growthbook#260]
Hi,
Trying to add Google Analytics as a Data Source it always, after clicking Authenticate with Google Analytics it always open the error page like below:
![image](https://user-images.githubusercontent.com/8244042/154305482-d34dea1e-db2d-42f6-888a-0b4694b52c84.png)

Steps to reproduce:
1. Login to GrowthBook dashboard
2. Go to Settings -> Data Sources
3. In the Data Source TYpe choose Google Analytics
4. Click Authenticate with Google Analytics button

Build: [0c98968](https://github.com/growthbook/growthbook/commit/0c989686e3a92f815e594765f1d6ae2cf28aa51a) (2022-02-13)

**Comment by jdorn** [comment]
Is this a self-hosted deployment? If so, you must create a Google OAuth application and set the credentials as environment variables. https://docs.growthbook.io/self-host/config#google-oauth-settings

**Comment by Fr3di** [comment]
Oh right, great. Must have missed that part.
Thx
