### ISSUE TITLE
Visual Experiment - opening the page and selecting elements

### ISSUE THREAD

**Issue by Fr3di** [growthbook/growthbook#261]
Hi,
In the Visual Editor, when I click Element Selector tool and click some of the clickable element of the page, it is doing the action, redirect to different page, opening modals etc.
How can I prevent this action to happen? It would be nice if only Interactive tool trigger the actions and Element Selector allow to just choose the element without triggering it's action (like inspector in browser)

Second improvements in my mind would be to add possibility to edit the classes, not just remove. (Edit option would i.e. show all class attributes that we could change etc)

Another issue is with the page which require the login action. When the grwothbook is only implement on the page for logged in users, how can I navigate to that page? When I try to open this url it redirects me to login page and Visual Editor shows that js scripts are not implemented so can not do anything else (can't log in to open the proper page)

The last problem that there is no any back button so when you click the button with Element Selector, it redirects you i.e. to the next page, there is no way to get back to the previous one.

Self hosted Build: [0c98968](https://github.com/growthbook/growthbook/commit/0c989686e3a92f815e594765f1d6ae2cf28aa51a) (2022-02-13)

**Comment by jdorn** [comment]
Hi!  Thanks for the feedback.  The current visual editor uses an iframe which has many limitations.  We are planning to rewrite it using a browser extension instead, which should solve most of the issues you brought up.  I don't have a specific timeline for that rewrite, but it will likely be at least a couple months.

**Comment by jdorn** [comment]
We have a new visual editor now.  Closing this issue.  If it's still relevant, please open a new one
