### ISSUE TITLE
[Feature] Ability to copy a feature override rule to all environments

### ISSUE THREAD

**Issue by AtakanColak** [growthbook/growthbook#2631]
### Description of Feature

At the moment we can copy a feature override rule to one environment, ability to copy it to all environments would be an enhancement.

**Comment by wisdomofgod** [comment]
We deployed the application using a branch with commit number 985a58e35376f86c55a0AF3a3ee584a7a683320. We encountered issues when using the copy function:
When I copy an experiment to another environment, both experiments have the same ID. If I change the settings of one experiment, the changes propagate to all environments.
I'm unsure  I used it incorrectly or  this is a bug.

**Comment by bryce-fitzsimons** [comment]
> We deployed the application using a branch with commit number 985a58e35376f86c55a0AF3a3ee584a7a683320. We encountered issues when using the copy function: When I copy an experiment to another environment, both experiments have the same ID. If I change the settings of one experiment, the changes propagate to all environments. I'm unsure I used it incorrectly or this is a bug.
@wisdomofgod 

This is sort of an unrelated quirk. If you want to have a different experiment in different environments, then you need to actually create/clone a new experiment for each environment.
