### ISSUE TITLE
[Bug] Add separate namespace id and display fields.

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#2666]
### Summary

The namespace `name` is used like both an id and display.  This is bad for a few reasons:
1. Changing the display name breaks all references to the namespace
2. The name might not be URL-safe, so creating a namespace with `#` in it for example, will break our API endpoints that are expecting the namespace id in the URL

We should:
1. Add separate `id` and `display` fields for namespaces instead of having a single "name" which acts as both.  `id` would be auto-generated and URL-safe.
3. Add a workaround to allow editing/deleting existing namespaces with non-url safe names

**Comment by august-growthbook** [comment]
Following
