### ISSUE TITLE
Additional environments

### ISSUE THREAD

**Issue by wrenzi** [growthbook/growthbook#269]
Hey there. 

We are studying if it is worth moving from Launchdarkly to a self-hosted **GrowthBook** instance. But there is a feature we are missing: The possibility to set up other environments besides dev and production, which is an essential use case at my company (local, dev, staging, demo, production). 

<img src="https://user-images.githubusercontent.com/1205251/155509233-ecc292c5-261d-4951-aca5-3b11ebcd8886.png" width="50%" />

Is there an easy way to achieve that?

**Comment by jdorn** [comment]
GrowthBook does support separate projects, each with their own features.

We built the feature flags in a way to support an arbitrary number of environments but we haven't built out the UI to manage that yet so everyone just gets the default dev/production environments currently. We are planning to launch custom environment support soon (next few weeks).

Right now we show both dev and production toggles on the main feature list page. How would you want that to work with 5 environments?

![image](https://user-images.githubusercontent.com/1087514/155538362-0def76ed-f31c-4f84-ab32-4707273d6ac6.png)

Also, would you want the exact same list of environments for all of the different projects?

**Comment by wrenzi** [comment]
Hey Jeremy, thanks for the prompt reply. 

It's good to know that GrowthBook is planning to launch the custom environment support soon.

Nowadays, we use a complete context per environment as shown in the image below. For instance: In the demo environment, we can enable a feature flag for a specific company's domain. This same feature can be 100% enabled in dev/local environments. And in production, this same feature can be enabled for only some companies' domains.

To make it clear, we are a B2B2C company, so we have specific rules according to the user company's domain.


![image](https://user-images.githubusercontent.com/1205251/155569434-b2c53c04-5035-4bc5-908d-4645a4d674b1.png)

**Comment by jdorn** [comment]
@wrenzi We added support for additional environments in the latest version.

**Comment by thangpham7793** [comment]
Hey @wrenzi probably not related to this but do you mind sharing why your company is considered moving off LaunchDarkly?
