### ISSUE TITLE
can't Add Data Source with empty password

### ISSUE THREAD

**Issue by clarkest** [growthbook/growthbook#270]
Attempt to add a new data source without a password produces a "Please fill out this field" pop up.  There's no way to conclude the add data source flow

**Comment by jdorn** [comment]
Which data source type is this for?

**Comment by clarkest** [comment]
Presto

**Comment by jdorn** [comment]
I can make password optional.  What about catalog and schema?  Those are also currently required.

**Comment by clarkest** [comment]
Having those optional would be ideal, too.  We use multiple schemas, and so all queries in our system need to specify schema anyway

**Comment by jdorn** [comment]
Ok, and just to double check.  We're currently using basic auth to connect to presto.  Do you want to keep using basic auth, but with an empty password?  Or do you want to not include auth headers at all?

**Comment by clarkest** [comment]
Basic is fine :)

**Comment by jdorn** [comment]
Just merged a fix for this.  Will take about 10 minutes to finish the build process.  Then you can pull the latest docker image and restart the container.
