### ISSUE TITLE
[Bug] Payload from Cloudflare KV using webhook doesn't work with init

### ISSUE THREAD

**Issue by arnarthor** [growthbook/growthbook#2713]
### Summary

When using a webhook to send data to Cloudflare KV and then using the `getPayloadFromKV` function to instantiate a Growthbook instance with the data the feature set is always empty.

This is due to the fact that the payload from KV includes webhook metadata that isn't parsed out.
The payload read from KV looks like this
```javascript
{
  type: 'payload.changed',
  timestamp: '2024-07-02T15:24:11.657Z',
  data: {
    payload: '{"features":{"phone-number-filter":{"defaultValue":"nova","rules":[{"condition":{"phone":{"$regex":"\\\\+62"}},"force":"twilio"},{"condition":{"phone":{"$regex":"\\\\+3547778"}},"force":"twilio"}]}},"dateUpdated":"2024-07-02T14:35:30.807Z"}'
  }
}
```
But the only thing that is supposed to be sent to the init function is the `data` part of that payload.
Additionally the payload that should be passed in, the `data` part, is a string, since it's a JSON value in KV that hasn't been parsed before being returned.

#### Expected Behavior

```javascript
const payload = await getPayloadFromKV(c.env);
const growthbook = new GrowthBook({
  apiHost: 'https://cdn.growthbook.io',
  clientKey: c.env.GROWTHBOOK_CLIENT_KEY,
});

await growthbook.init({
  payload,
});
```

This code snippet which is taken from [this documentation](https://docs.growthbook.io/lib/edge/cloudflare#manual-sdk-integration-on-edge) should work

#### Current Behavior

To pre populate the feature set I need to add this additional code with relevant typescript hacks to make it work

```typescript
const payloadFromKv = await getPayloadFromKV(c.env);
const growthbook = new GrowthBook({
  apiHost: 'https://cdn.growthbook.io',
  clientKey: c.env.GROWTHBOOK_CLIENT_KEY,
});
try {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const payload = JSON.parse((payloadFromKv as any).data.payload);
  await growthbook.init({
    payload,
    streaming: false,
  });
} catch (e) {
  debugLog({ message: 'Using default init with request' });
  await growthbook.init();
}
```

**Comment by bryce-fitzsimons** [comment]
Addressed in https://github.com/growthbook/growthbook-proxy/issues/61
