### ISSUE TITLE
[Bug] Adding a feature via API does not append specified tags

### ISSUE THREAD

**Issue by reuben-tonna-ixaris** [growthbook/growthbook#2729]
### Summary

I am trying to create a feature via an api call.  I am using a self-hosted service running in docker using the docker-compose sample provided in the docs. pages.

Here is the request

POST http://localhost:3100/api/v1/features
{
    "id": "dark-mode4",
    "description": "Dark mode",
    "archived": false,
    "owner": "test-app",
    "project": "prj_40645322lyfvtzsz",
    "valueType": "boolean",
    "defaultValue": "false",
    "tags": [
        "Active"
    ]
}

#### Expected Behavior

I expect the tags array in the response to contain "Active", and also in the UI to see the tag.

#### Current Behavior

The response, shown below, shows that the 'tags' array is empty.  And looking in the UI no tags are assigned to my new feature flag.

{
    "feature": {
        "id": "dark-mode4",
        "description": "Dark mode",
        "archived": false,
        "dateCreated": "2024-07-10T14:21:02.969Z",
        "dateUpdated": "2024-07-10T14:21:02.969Z",
        "defaultValue": "false",
        "environments": {
            "production": {
                "enabled": false,
                "defaultValue": "false",
                "rules": []
            },
            "pre-production": {
                "enabled": false,
                "defaultValue": "false",
                "rules": []
            },
            "qa": {
                "enabled": false,
                "defaultValue": "false",
                "rules": []
            },
            "qa-perf": {
                "enabled": false,
                "defaultValue": "false",
                "rules": []
            }
        },
        "owner": "test-app",
        "project": "prj_40645322lyfvtzsz",
        "tags": [],
        "valueType": "boolean",
        "revision": {
            "comment": "",
            "date": "2024-07-10T14:21:02.969Z",
            "publishedBy": "",
            "version": 1
        }
    }
}

**Comment by reuben-tonna-ixaris** [comment]
Note I also tried creating the tag in the UI via Settings->Tags and then making the API call.  Still not assigned.

**Comment by august-growthbook** [comment]
It appears that we may not be detecting the "tags" at all for the POST request for that endpoint. The associated file doesn't have any reference to tags:

It should be happening somewhere in here:

https://github.com/growthbook/growthbook/blob/3fe6181d3c0ff6411348c428d1fa05d6545ce845/packages/back-end/src/api/features/postFeature.ts#L86-L112

But the file doesn't contain any references to "tags".

**Comment by romain-growthbook** [comment]
Fixed in 2ec26c406c642dcf17abf05706e796fe7ba53ab4

**Comment by romain-growthbook** [comment]
Thanks for reporting!
