### ISSUE TITLE
Question about segments

### ISSUE THREAD

**Issue by wrenzi** [growthbook/growthbook#274]
Hey folks, another question: To have a feature flag configured according to simple segments (for instance, a group with a given email domain, and from a specific country), do I have to connect my database? Am I not able to do it manually?

![image](https://user-images.githubusercontent.com/1205251/156007399-2000a372-cd75-460a-ad41-58667460cf5b.png)

**Comment by jdorn** [comment]
Segments are only used when analyzing experiment results, not for feature flags.  We're pushing a change to the left nav soon that will hopefully reduce confusion around that.

For features, you would use targeting attributes instead.  

First, set the list of attributes you want for your app under Settings.

Then, pass those attributes into the SDK:

```ts
new GrowthBook({
  attributes: {
    email: "test@example.com",
    country: "US",
    ...
  }
})
```

And then, you can add an override rule for a feature with a targeting condition:

- Email matches pattern "@example.com"
- Country is equal to "US"
