### ISSUE TITLE
[Bug] Redirects with multiple controls will always render the control and never the variant.

### ISSUE THREAD

**Issue by natasha-growthbook** [growthbook/growthbook#2741]
### Summary

When you have a redirect URL with multiple controls, the control is always rendered and never the variant.

### Replication Steps

- Configure experiment with 2 controls and 1 variant with each control being 25% traffic and variant being 50% traffic

<img width="752" alt="2024-07-15_11-00-22" src="https://github.com/user-attachments/assets/3fa526db-fdd3-47ac-a8f7-416acb3c113a">
<img width="781" alt="2024-07-15_11-01-01" src="https://github.com/user-attachments/assets/d498ab58-6fcc-4660-bf2f-26c6be624541">

#### Expected Behavior

Redirect URL control sent to 50% of the users and other 50% redirected to variant URL

#### Current Behavior

All users rendered the control URL

### Workaround

Configure Experiment with 50% control and 50% variant (no second control configured).

**Comment by bryce-fitzsimons** [comment]
can we confirm this is really happening? i'm not able to reproduce it

**Comment by natasha-growthbook** [comment]
Hi Bryce,

I can still replicate this on my end.

Please, see replication steps and video below:

Create experiment with 25% control, 25% control 1 and 50% variant:
<img width="770" alt="2024-07-18_10-59-16" src="https://github.com/user-attachments/assets/5ace994e-d466-442d-b01b-8ff31df278f3">

Set up URL redirect using HTTP script implementation so that control and control 1 do not redirect and the variation redirect
<img width="780" alt="2024-07-18_10-59-48" src="https://github.com/user-attachments/assets/102808a5-f245-4c7b-9f7c-4e4429d3

Results:
https://github.com/user-attachments/assets/dbb7a9be-913b-4eee-a398-07a6e8c5ce136fe3">

Left the experiment running so you can test the user experience when going to the https://wecareliving.co.uk/ URL.
