### ISSUE TITLE
Pendo Intigration

### ISSUE THREAD

**Issue by mandadimuralidharreddy** [growthbook/growthbook#281]
Hi
Is there any plans to integrate with pendo.io

**Comment by jdorn** [comment]
Pendo allows you to export event data to BigQuery, Redshift, or Snowflake.  GrowthBook supports all 3 of those currently.

In the future, we may build a direct integration with the Pendo API, but it's not currently on our short term roadmap.

**Comment by mandadimuralidharreddy** [comment]
Thank you. I will close this ticket.
