### ISSUE TITLE
Add posthog as data source

### ISSUE THREAD

**Issue by IgnusG** [growthbook/growthbook#284]
Would be cool if posthog (semi OSS analytics platform) would be supported. It supports feature flags natively but they feel more limited then growthbook's. 

https://posthog.com

**Comment by Auz** [comment]
Thanks for the suggestion. We will look into how we might integrate.

**Comment by jdorn** [comment]
If you are self-hosting PostHog, you could point GrowthBook to the underlying Postgres or ClickHouse database.
