### ISSUE TITLE
[Bug] Adding/removing visual experiment variants doesn't update experiment phase weights

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#2858]
![visual-changeset-bug-compressed](https://github.com/user-attachments/assets/873c721a-bb30-45ab-a5ec-6a9d73367d06)

Updating the variants in a visual editor experiment, does not change the phase.variationWeights.

**Comment by gavrashenko** [comment]
Are there any updates? It looks like a critical bug because it’s not just a visual inconvenience; it breaks the weights configuration.
