### ISSUE TITLE
Enable robots.txt Support for API Subdomains

### ISSUE THREAD

**Issue by fabianmarinog** [growthbook/growthbook#2865]
We have observed that our Features API hosted on a subdomain is being indexed by Google. To prevent search engines from crawling and indexing this subdomain, we need to serve a robots.txt file that disallows bots.  We propose adding support for serving the robots.txt file from the GrowthBook backend.

One potential solution is to amend the api.routers.ts file within the packages/backend/api directory to include a new route specifically for robots.txt.

**Comment by august-growthbook** [comment]
Hi @fabianmarinog Thanks for the feature suggestion! @Kevin-Chant is going to be working on this soon.

**Comment by Kevin-Chant** [comment]
@fabianmarinog just to check, would the desired path be `/api/v1/robots.txt` or `/robots.txt` (both under the backend domain, e.g. locally `localhost:3100/`)?

**Comment by fabianmarinog** [comment]
@Kevin-Chant  the desired path is `/robots.txt` under the backend domain. Thank you.
