### ISSUE TITLE
[Bug] When Code refs is enabled, default tab is code refs, not overview

### ISSUE THREAD

**Issue by aa-mark-green** [growthbook/growthbook#2914]
### Summary

When code refs is not enabled, clicking on a feature takes to you to a page without any breadcrumb and shows you the overview page.  For example:

https://app.growthbook.io/features/show-percentages-in-pie-charts-2022-11-28

When you enable code refs, clicking on this link takes you to the code refs page and not the overview page.

#### Expected Behavior

It should default to the overview page so legacy links don't change what they show depending on whether or not code refs is enabled.

#### Current Behavior

That link takes you to overview page if no code refs and the code refs page if code refs is enabled.

**Comment by bryce-fitzsimons** [comment]
Pushed a fix for this. It was due to a bug with localStorage keys.
