### ISSUE TITLE
[Bug] Fallback Attribute selection is missing on New Override Rule modal

### ISSUE THREAD

**Issue by august-growthbook** [growthbook/growthbook#2938]
### Summary

If designing a new Experiment from scratch, it's possible to set a fallback attribute.
If adding an Experiment rule from within a feature flag, there isn't the option to set a fallback attribute.

![fallback_attrs](https://github.com/user-attachments/assets/cbbbf0a5-8996-40ea-a11a-bddb15ada465)

If you want to use Scenario #2 in the screenshot above, you can still add a fallback attribute in the "Targeting and Traffic" section on the Experiment's "Overview" tab.

#### Expected Behavior

There should be a Fallback Attribute selection on the "New Override Rule" modal.

#### Current Behavior

There is no Fallback Attribute on the "New Override Rule" modal

**Comment by krzyzawa** [comment]
Looks like there is also an issue with fallback definition when creating an experiment. It might be related to this bug. Fallback id does not get saved and does not show up in SDK experiments response payload, after creating an experiment. There is a workaround, when experiment is created then you can edit it and add fallback id again, then it works and shows up in /api/features/ in fallbackAttribute key

**Comment by august-growthbook** [comment]
Fixed by https://github.com/growthbook/growthbook/pull/2964

**Comment by august-growthbook** [comment]
Closing
