### ISSUE TITLE
[Bug] Silently Failing Queries

### ISSUE THREAD

**Issue by fabianmarinog** [growthbook/growthbook#2954]
**Expected behavior when a query fails:**

GrowthBook reports detailed queries in the report view and in the query details view.

**Actual Behavior when a query fails:**

GrowthBook does not report failing queries in the report view, but in the query details view.

**Steps to reproduce:**

1. Add a known failing metric to a custom report
2. Use a Dimension in the configuration of the report to break down results for metrics
3. Click Refresh Data
4. Wait for the queries to finish/fail and Observe

A warning in the report shows there is an error with a query: 
![Image](https://github.com/user-attachments/assets/901cb71d-b06d-4c7e-a9c8-f08ac76fba76)
No error warning shows up. Instead, the metric just shows "no data" in the report:
![Image](https://github.com/user-attachments/assets/72557d0f-c566-4b1f-8741-cfdc9c611723)

GrowthBook Build: add1cb2 (2024-07-24)

**Comment by lukesonnet** [comment]
(closed this out, thanks for the bug report!)
