### ISSUE TITLE
[Bug] CSV export of report doesn't include dimensions

### ISSUE THREAD

**Issue by itsgrimetime** [growthbook/growthbook#2975]
### Summary
When using the "Export to CSV" button on a custom report that's slicing by a specific dimension, the dimension column isn't included in the output.

#### Expected Behavior

There should be one row per dimension/variation pair for each metric

#### Current Behavior

There is only one row per variation for each metric

**Comment by lukesonnet** [comment]
There are a variety of issues with Reports and dimensions, it seems (#2954). We've been hoping to overhaul this system but haven't gotten around to it.

I'll take a look to see if we can patch these 2 issues.
