### ISSUE TITLE
Packaging issues - gbstats

### ISSUE THREAD

**Issue by qbatten** [growthbook/growthbook#298]
## Summary

This is really two closely-related issues:
1. gbstats isn't properly packaged for use by pip.
2. gbstats's poetry config is improperly configured as well (I think?)

I'm happy to drop a PR in that implements my suggested changes, if you'd like (or a variation on them if you have alternatives), just lmk. Suggested changes:
 1. Adds an up-to-date requirements file
 2. Removes optional flag from all reqs in the tool.poetry.dependencies block in pyproject.toml. 
 3. (optional, could be nice) Add a build command to the package.json file that calls the poetry export command

## 1. pip packaging

- Problem: gbstats doesn't have a requirements.txt or pipfile, so pip is unaware of any dependencies. 
- Expected behavior: `pip install gbstats` installs gbstats + dependencies; pip is able to manage gbstats correctly.
- Observed behavior: pip installs only gbstats. `pip show` shows that pip is unaware of any dependencies.

Suggested resolution is that some kind of export from poetry reqs to pip-compatible reqs is included in your build system. The command that poetry [offers to export its requirements](https://python-poetry.org/docs/cli#export) is `poetry export -f requirements.txt --output requirements.txt`. Running this before a release would be sufficient, I think. 

## 2. poetry config

Currently, all dependencies in the pyproject.toml are marked as "optional." As a result, when I try to install dependencies using poetry, it skips every package. Further, because the optional dependencies are all in the main dependency block, there isn't a straightforward (or any???) way to actually install them from cli. I had to go in and remove the optional flag from them all in the pyproject.toml file. Doing so resolved my issue. 

(Note: This was really confusing and figuring out the problem ate up over an hour of my time; I'd mark this as a major blocker to contribution)

**Comment by jdorn** [comment]
Hi @qbatten , happy to merge a PR if you make one for these issues.  Thanks for taking the time to debug them.
