### ISSUE TITLE
What is the difference between user_id and anonymous_id?

### ISSUE THREAD

**Issue by julisch94** [growthbook/growthbook#301]
Hey there, I hope this is the correct place to ask this question. I can see several example usages of `user_id` and `anonymous_id` in the documentation but I somehow can't find an explanation of the different purposes. When should I be using `user_id` and when should I be using `anonymous_id`?

If it is in the documentation and I was just too blind to see it, please point me to the article. Thanks!

**Comment by lukesonnet** [comment]
Sorry for the unclear documentation. You can define any ID type that you have in your data warehouse. Defining them in GrowthBook allows you to link IDs across your metrics, dimensions, experiments, etc.. 

`user_id` and `anonymous_id` These are just two common examples that people use.
