### ISSUE TITLE
[Bug] Saved Group Delete

### ISSUE THREAD

**Issue by fivesmallq** [growthbook/growthbook#3041]
### Summary

The saved group can be deleted on the internal edit page, even if a feature uses the group

#### Expected Behavior
<img width="1381" alt="image" src="https://github.com/user-attachments/assets/96101bd9-ebb1-4886-900b-33fe8294717b">

#### Current Behavior

Now it cannot be deleted on the external page, but the details page can.

<img width="1402" alt="image" src="https://github.com/user-attachments/assets/5f81d499-a7b3-4972-b31b-48a7bab9e547">

**Comment by lukesonnet** [comment]
Closed by #3037
