### ISSUE TITLE
[Bug] V2 hashing option is not saved in Experiment rules

### ISSUE THREAD

**Issue by fabianmarinog** [growthbook/growthbook#3046]
### Summary

The V2 hashing option is not saved when creating new experiment rules in the self-hosted version of GrowthBook, V1 is shown instead.

#### Expected Behavior

When selecting V2 Hashing Algorithm, in the Experiment rule creation form, the V2 option is saved.

#### Current Behavior

When selecting V2 Hashing Algorithm, in the Experiment rule creation form, the V1 option is saved.

https://github.com/user-attachments/assets/99ee6022-a88d-418a-84cd-84f655db0901

**Comment by august-growthbook** [comment]
Hi Fabian, thanks for reporting this. Are you able to upgrade to the latest Build 3.3 and see if this is still an issue in that version?

**Comment by fabianmarinog** [comment]
@august-growthbook I see. I've installed the latest non-stable release ([3.2.0+b7201bb](https://github.com/growthbook/growthbook/commit/b7201bbd5fcb3ea6e3d1bd3b3b0e1ade21cd7023)) and it's fixed. Should we wait until the new release to close this bug?

**Comment by lukesonnet** [comment]
@bryce-fitzsimons let's make sure this is fully resolved in the latest 3.3 build.
