### ISSUE TITLE
[Feature] REST API : Ability to set the Conversion Window Override

### ISSUE THREAD

**Issue by natasha-growthbook** [growthbook/growthbook#3108]
### Description of Feature

The ability to set the set "Conversion Window override" Using the REST API so I can select whether to respect or ignore the conversion window. In this example I wish to choose to ignore the conversion window and have to select this manually on the UI.

**Comment by HenrikHallatorp** [comment]
Would be helpful for us :)

**Comment by lukesonnet** [comment]
This is currently covered by the `attributionModel` setting. If you want to ignore conversion windows, set it to `"experimentDuration"`. If you want to respect conversion windows, set it to `"firstExposure"`.

Sorry this is unclear, I'm adding a note to our API documentation.
