### ISSUE TITLE
OpenAPI Spec

### ISSUE THREAD

**Issue by lukef** [growthbook/growthbook#312]
Do you have an OpenAPI spec available? I'd love to make a new client and it would be extremely helpful to have.

**Comment by jdorn** [comment]
Our SDKs are not API driven so I don't think an OpenAPI spec would make sense.  We do have extensive docs on how to build your own client library including data structures, algorithms, and 200+ unit test cases - https://docs.growthbook.io/lib/build-your-own

**Comment by tinahollygb** [comment]
An OpenAPI spec is available for our [REST API in the docs](https://docs.growthbook.io/api/). You can click the Download button to get it. Let us know if you have any issues with it.
