### ISSUE TITLE
[Bug] Metric Analysis doesn't work with non-nullable date column type in ClickHouse

### ISSUE THREAD

**Issue by syabruk** [growthbook/growthbook#3129]
### Summary

"Metric Analysis" tab on a metric page fails to execute a query when using a ClickHouse client.

#### Expected Behavior

Metric Analysis builds the following subquery for calculating overall statistics:
```sql
__statisticsOverall AS (
  SELECT
    CAST(NULL AS DATE) AS date /* A line with the issue */
    , MAX(toString('overall')) AS data_type
    , 'capped' AS capped
    , COUNT(*) as units
    , SUM(LEAST(toFloat64(COALESCE(value, 0))
    , 45
)
```

The issue can be fixed by using non-nullable date column type:
```sql
clickhouse.local :) select CAST(NULL AS Nullable(DATE));

SELECT CAST(NULL, 'Nullable(DATE)')

Query id: 158cd269-5ad1-47d2-adde-1a2806546777

   ┌─CAST(NULL, 'Nullable(DATE)')─┐
1. │                         ᴺᵁᴸᴸ │
   └──────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.
```

`castToDate` function can be added to `packages/back-end/src/integrations/ClickHouse.ts`. Example:

```ts
castToDate(col: string): string {
  const columType = col === "NULL" ? "Nullable(DATE)" : "DATE";
  return `CAST(${col} AS ${columType})`;
}
```

#### Current Behavior

`Date` column type is non-nullable in ClickHouse and because of that `CAST(NULL AS DATE)` doesn't work:
```sql
clickhouse.local :) select CAST(NULL AS DATE);

SELECT CAST(NULL, 'DATE')

Query id: e29b3f2d-f583-4913-bb5a-992fd0479530


Elapsed: 0.067 sec.

Received exception from server (version 24.8.2):
Code: 70. DB::Exception: Received from clickhouse.local:9000. DB::Exception: Cannot convert NULL to a non-nullable type: In scope SELECT CAST(NULL, 'DATE'). (CANNOT_CONVERT_TYPE)
```

<img width="917" alt="image" src="https://github.com/user-attachments/assets/de3f3426-9b0d-45de-ae3f-3b65a98ecc66">

<img width="927" alt="image" src="https://github.com/user-attachments/assets/87b5c18d-91dd-483f-b6d8-02902a1fb76f">

**Comment by lukesonnet** [comment]
Thank you for this super clear bug report and reasonable suggested fix! Implemented and is in our `latest` build and will be part of our next numbered release.
