### ISSUE TITLE
Metrics page will not load when a large number of metrics are loaded.

### ISSUE THREAD

**Issue by stephen-theadventurepeople** [growthbook/growthbook#3152]
### Summary

Metrics page will not load when a large number of metrics are loaded. 

25/10/24 Follow up : Only occurs if the extension "React Developer Tools" is enabled

#### Expected Behavior

The metrics page should load as normal no matter the number of metrics loaded into the system

#### Current Behavior

Currently we have over 2000 metrics which have been auto discovered from our BigQuery integration.  When attempting to manage these metrics the page will crash. I suspect this is due to the page rendering all metrics instead of paging them in.

**Comment by lukesonnet** [comment]
This should be resolved by #3233 which adds pagination.
