### ISSUE TITLE
Fix language for experiments in the future

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#318]
When there are not enough results, we tell the user that the experiment just started, so come back later. When the experiment dates are set to a future time, this language doesn't fit very well. We should adjust the language to take this future state into account when figuring out the message. 

<img width="875" alt="CleanShot 2022-04-10 at 21 23 22@2x" src="https://user-images.githubusercontent.com/46107/162642125-362a52c0-7949-418c-80d6-24e8361579fd.png">

It should say something like "This experiment hasn't started and has no data yet. Update the results in/at N minutes/days/date"

**Comment by sathithyayogi** [comment]
shall i take this issue ?

**Comment by Aashish-Upadhyay-101** [comment]
@Auz is this open to work? If yes I would like to work on this !

**Comment by ptdatta** [comment]
Hey @Auz Can I give it a try?
