### ISSUE TITLE
SSL error on email setup

### ISSUE THREAD

**Issue by tabz24** [growthbook/growthbook#320]
I am trying to self-host, everything is working so far except the emails. These are my email configuration 
`EMAIL_ENABLED: true`
`EMAIL_HOST: xxxxxxxx`
`EMAIL_PORT: 587`
`EMAIL_HOST_USER: xxxxxxxx`
`EMAIL_HOST_PASSWORD: xxxxxxxx`
`EMAIL_FROM: xxxxxxxx`
`EMAIL_USE_TLS: false`
I have tried `EMAIL_USE_TLS: true` as well

I keep getting following the error 
`Error sending email: Error: :error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:`

I couldn’t find anything that would fix the error, any idea what I might be doing wrong?

**Comment by jdorn** [comment]
What email service are you using?  You can try setting `EMAIL_USE_TLS` to true and use port `465` to see if that works.

**Comment by tabz24** [comment]
I am using rapidmail and they only accept connections at 587

**Comment by marcoadasilvaa** [comment]
Same problem here with mandrillapp smtp service

**Comment by jdorn** [comment]
I just simplified the SMTP settings and fixed a bug when using port `587`.  Let me know if you are still experiencing issues after this change.

You now no longer need to specify `EMAIL_USE_TLS`.  If using port 465, it will always use TLS.  For all other ports, it will start with a plain connection and upgrade using StartTLS if supported.

**Comment by marcoadasilvaa** [comment]
@jdorn Thanks for your support, version: git-d4b4141 is OK!

**Comment by tabz24** [comment]
It's working fine now, thanks a lot @jdorn
