### ISSUE TITLE
[Bug] Metric Window is set to "Conversion Window" by default

### ISSUE THREAD

**Issue by natasha-growthbook** [growthbook/growthbook#3203]
### Summary

By default the metric window is set to  "conversion window" instead of "none" as shown in the docs [here](https://docs.growthbook.io/app/metrics#metric-windows)

#### Expected Behavior

By default the metric window is set to "none"

#### Current Behavior

The metric window is set to "conversion window" by default.

**Comment by lukesonnet** [comment]
This is a documentation error, the default, for historical reasons on classic metrics, is a 72 hour conversion window. We'll either update the behavior or fix the docs.

Thanks for reporting.
