### ISSUE TITLE
[Bug] Environment specific users with Experimenter permissions cannot edit experiments

### ISSUE THREAD

**Issue by natasha-growthbook** [growthbook/growthbook#3248]
### Summary

When you create a "experimenter" role for a user that is tied to an environment, the user does not have edit access to the experiments.

#### Replication steps

Create user with experimenter role that is restricted to specific environment:

<img width="501" alt="image" src="https://github.com/user-attachments/assets/8ab2b24b-ebff-464c-840d-835857344d41">

User can edit features but not experiments:

<img width="1555" alt="image" src="https://github.com/user-attachments/assets/99722aa3-8cea-46d0-82b4-df16f2567cc0">

#### Expected Behavior

Environment specific users with the experimenter permissions can edit experiments

#### Current Behavior

Environment specific users with the experimenter permissions cannot edit experiments

**Comment by mknowlton89** [comment]
@natasha-growthbook I just merged this PR (https://github.com/growthbook/growthbook/pull/2835) and this should also improve the behavior described here.

**Comment by natasha-growthbook** [comment]
Thank you for the update @mknowlton89
