### ISSUE TITLE
Deleting and re-creating user accounts - possible bug

### ISSUE THREAD

**Issue by cpnat** [growthbook/growthbook#325]
We have encountered some strange behavior when deleting and re-adding a user through the Growthbook web UI.  

It seems that Growthbook has the concept of an organization and a user; when the button to delete a user is clicked, it is calling this endpoint:-

https://github.com/growthbook/growthbook/blob/7207ed60634482651f08f186e31a35f3802a6b24/packages/back-end/src/app.ts#L359

https://github.com/growthbook/growthbook/blob/a8563254c040462201942cfd0be48cf7f97d9f37/packages/back-end/src/services/organizations.ts#L132

This logic removes the user from the organization, but does not delete the user. 

If you re-create the user later  and send an invite link there is a conflict - the user already exists and the account cannot be re-created.

Is this behavior intentional? Currently we are resorting to deleting the user manually from the database before setting up an invitation (where they had a previous account that was deleted).

**Comment by jdorn** [comment]
Closing this issue.  If it is still relevant in the latest GrowthBook version, please create a new one
