### ISSUE TITLE
Recent `SqlIntegration` commit broke importing experiments for BigQuery

### ISSUE THREAD

**Issue by fastfedora** [growthbook/growthbook#329]
As part of the `SqlIntegration` refactor, the query used to import experiments created in `getPastExperimentQuery` was refactored. The new query uses a `UNION` statement to join the experiment tables. 

While standard SQL allows an unqualified `UNION`, BigQuery requires `UNION` statements to be qualified with either `ALL` or `DISTINCT`. Since `UNION` and `UNION DISTINCT` should be equivalent in standard SQL, this can be fixed by adding `DISTINCT` after the `UNION` statement on [this line](https://github.com/growthbook/growthbook/blob/07472c5091025e63c645637795c003c4501f4aad/packages/back-end/src/integrations/SqlIntegration.ts#L192). 

This causes the following error to appear within GrowthBook when pressing Add Experiment:

![image](https://user-images.githubusercontent.com/1173892/166345539-2634e73c-2be9-4fa2-92f3-eb7089dcdd9e.png)

**Comment by jdorn** [comment]
Thanks for catching this.  I confirmed `UNION DISTINCT` works in all supported SQL data sources.  Interestingly, that syntax is undocumented for Postgres, Snowflake, and Redshift although the queries still seem to work.  I'll push up a fix soon
