### ISSUE TITLE
[Feature] Allow metrics to be sorted from the experiment report

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#3296]
Currently for experiment reports, metrics are only sortable via the add metrics modal. When users have a lot of metrics, this is not a great UI to let users sort.

**Comment by lukesonnet** [comment]
This can be improved, but it is not strictly true that this is the only way they are sortable. If you use [Metric Groups](https://docs.growthbook.io/app/metrics#metric-groups) you can sort metrics within a metric group if you add the metric group to your experiment.
