### ISSUE TITLE
New experiment dimension not recognized in running experiment

### ISSUE THREAD

**Issue by fastfedora** [growthbook/growthbook#332]
I'm working on my first experiment within GrowthBook. After I created the experiment, I realized it would be useful to have the user cohort as a dimension for analysis. So I went and added it to my data source. However, the dimension still doesn't show up under the Results tab in the Dimension drop-down. How do I add a dimension to a running experiment, or can experiment dimensions only be added when experiments are created?

For reference, here is how I defined my Logged In User data source to retrieve the user cohort from Google Analytics using Big Query:

```
SELECT
  user_id,
  user_pseudo_id as anonymous_id,
  TIMESTAMP_MICROS(event_timestamp) as timestamp,
  experiment_id_param.value.string_value AS experiment_id,
  variation_id_param.value.int_value AS variation_id,
  user_cohort_param.value.string_value AS cohort,
  geo.country as country,
  traffic_source.source as source,
  traffic_source.medium as medium,
  device.category as device,
  device.web_info.browser as browser,
  device.operating_system as os
FROM
  `do-staging`.`analytics_186599738`.`events_intraday_*`,
  UNNEST(event_params) AS experiment_id_param,
  UNNEST(event_params) AS variation_id_param,
  UNNEST(user_properties) AS user_cohort_param
WHERE
  _TABLE_SUFFIX BETWEEN '{{startYear}}{{startMonth}}{{startDay}}' AND '{{endYear}}{{endMonth}}{{endDay}}'
  AND event_name = 'experiment_viewed'  
  AND experiment_id_param.key = 'experiment_id'
  AND variation_id_param.key = 'variation_id'
  AND user_cohort_param.key = 'cohort'
```

And here is how I defined the Anonymous Visitor query:

```
SELECT
  user_id,
  user_pseudo_id as anonymous_id,
  TIMESTAMP_MICROS(event_timestamp) as timestamp,
  experiment_id_param.value.string_value AS experiment_id,
  variation_id_param.value.int_value AS variation_id,
  'anonymous' AS cohort,
  geo.country as country,
  traffic_source.source as source,
  traffic_source.medium as medium,
  device.category as device,
  device.web_info.browser as browser,
  device.operating_system as os
FROM
  `do-staging`.`analytics_186599738`.`events_intraday_*`,
  UNNEST(event_params) AS experiment_id_param,
  UNNEST(event_params) AS variation_id_param
WHERE
  _TABLE_SUFFIX BETWEEN '{{startYear}}{{startMonth}}{{startDay}}' AND '{{endYear}}{{endMonth}}{{endDay}}'
  AND event_name = 'experiment_viewed'  
  AND experiment_id_param.key = 'experiment_id'
  AND variation_id_param.key = 'variation_id'
```  

Two notes on how this differs from the standard BigQuery queries:

 - The event name is `experiment_viewed` not `viewed_experiment` because we're using the `object_action` naming standard for events
 - I'm currently using the `events_intraday` tables for testing, since it's updated in real-time. Once I have everything working, I'll switch to the normal `events_` tables

**Comment by jdorn** [comment]
In addition to modifying the query, you also need to add it to the list of Dimension Columns:

![image](https://user-images.githubusercontent.com/1087514/166389594-30087c0a-034b-4897-b4aa-2aab19bb11ac.png)

Also, it looks like you are hard-coding the cohort for the anonymous visitors.  You can just get rid of that column completely from that query.  The list of dimension columns are defined separately for each assignment query.

**Comment by fastfedora** [comment]
Thanks, that worked. I totally missed that field when editing the query. I also removed it from the anonymous query.
