### ISSUE TITLE
[Bug] Do not allow to create feature in a project that does not belong to an org

### ISSUE THREAD

**Issue by spanishkangaroo** [growthbook/growthbook#3343]
#### Expected Behavior

Do not allow to create feature in a project that does not belong to an org. 
Return a meaningful error message, explicitly stating that the project that does not exist (in that org, at least).

#### Current Behavior

The feature gets created even when the project does not exist in the org, but then shows "Invalid project" in the UI.

![image](https://github.com/user-attachments/assets/182317fb-2725-4f6d-b2a9-48e5a05a00b3)

**Comment by mknowlton89** [comment]
@spanishkangaroo For context, are you experiencing this when creating features via the REST API?

**Comment by spanishkangaroo** [comment]
> Return a meaningful error message, explicitly stating that the project that does not exist (in that org, at least).

Sorry, yes, but I see you already got it, thanks!
