### ISSUE TITLE
[Feature] Add delete feature to API operations

### ISSUE THREAD

**Issue by spanishkangaroo** [growthbook/growthbook#3346]
### Description of Feature

Add delete feature to API operations.
Nowadays, there is no way to delete a feature through the API. 
The use of a RESTFUL operation with the DELETE verb should be added to avoid manual deletion from the UI, which is not viable in most enterprise scenarios.

**Comment by mknowlton89** [comment]
@spanishkangaroo This is being deployed right now and should be available in the next ~15 minutes. Thanks for the suggestion!
