### ISSUE TITLE
Webhook displays as not fired, when it might have fired

### ISSUE THREAD

**Issue by Shumuu** [growthbook/growthbook#336]
Sorry for the confusing title, so let me explain in detail!

We Self Host Growthbook and it runs on a single Server with multiple other Containers.

Production Frontend
Production Growthbook

Staging Frontend
Staging Growthbook

We manage these Containers with [Traefik](https://doc.traefik.io/traefik/). So a Problem we had was that the Webhooks weren't firing BUT in truth Docker saw the URL/Domain, it resolved to it's own IP and I guess it did a localhost request ? Not sure what it exactly does then but it just never arrived.

The Solution was to add a `extra_hosts` property to Docker and now the Webhook arrives and displays as fired.

Since there was no indication if the Webhook did fire, it was difficult to find the solution. I'm sure the Webhook did fire, but just never arrived, so maybe there could be an indication that it did fire.

**Comment by Shumuu** [comment]
Well, if it got a 200 response, it should have shown it has been fired - which it hasn't. It simply displayed as `never fired`.

The docker container, or rather the script/webhook endpoint, did not receive a request, so I am unsure if it could've gotten a response.

Does the webhook display an error if it received any non 200 response code ?

**Comment by jdorn** [comment]
Yes, it should show an error for any non-200 response, so it's likely the webhook never attempted to fire in the first place.  What change did you make to features that was supposed to trigger the webhook?

**Comment by Shumuu** [comment]
I toggled a Feature to be off/on in production. As soon as I added the `extra_hosts` property, it worked. Without it, it just never showed if it fired or not.

**Comment by jdorn** [comment]
We have a new Webhooks framework now.  Please create a new issue if this is still relevant.
