### ISSUE TITLE
Java SDK support

### ISSUE THREAD

**Issue by janko-sokolovic** [growthbook/growthbook#338]
What are the plans for including JVM SDK?

**Comment by thangpham7793** [comment]
Piggy-backing @janko-sokolovic  any plans for .NET as well?

**Comment by darklordzw** [comment]
I recently finished a .NET port of the SDK! You can find it below:

NuGet link: https://www.nuget.org/packages/growthbook-c-sharp/
GitHub repo: https://github.com/darklordzw/growthbook-c-sharp

The port was pretty straightforward, didn't take very long. If anyone wants to tackle a Java port, the .NET one might be a good reference to get you started.

**Comment by DNAlchemist** [comment]
@janko-sokolovic 
I am using Kotlin SDK from Java.
Is this option not suitable?
For some reason it is written that it is for Android, I really do not understand why yet.

**Comment by bpoweski** [comment]
We have the same need - a JVM based client library.

**Comment by janko-sokolovic** [comment]
I've hacked out a port for backend usage from android code. Testing it a bit now.
Will try to clean it up a bit and propose a PR

**Comment by DNAlchemist** [comment]
@bpoweski @janko-sokolovic 
SDK for java was published by Growthbook team
https://docs.growthbook.io/lib/java

**Comment by tinahollygb** [comment]
We now have a Java SDK that works on the JVM and on Android. There are code examples in Android Java, Java Spring, and Kotlin with Ktor. See the docs and the code examples linked at the bottom of the page: https://docs.growthbook.io/lib/java
