### ISSUE TITLE
Experiment view is broken after adding a third "Experiment Assignment Query" to Data source

### ISSUE THREAD

**Issue by andehen** [growthbook/growthbook#341]
After changing a "Data source" (adding a new "Identifier Type" and a "Experiment Assignment Query"), all the experiment views for that data source is broken. Happens somewhere in JS in the browser. The error is still there after reverting the change to the data source.

Experiments configured for other data sources works just fine.

UPDATE: Just reproduced this in another environment now. Happens when a third "Experiment Assignment Queries" is added. Does not help to delete it in UI (soft delete?). Have not tried to delete it in db yet.

UPDATE 2: By looking at where the error is thrown in the compiled code (see image 3), [this](https://github.com/growthbook/growthbook/blob/c29cf54737173ce4d7ce7cef3f6debce187ce096/packages/front-end/pages/experiment/%5Beid%5D.tsx#L656) seems to be the line where the `TypeError: Cannot read properties of null (reading 'name')` error is thrown.

![2022-05-10_19-07](https://user-images.githubusercontent.com/754494/167684555-993c3a3d-dde4-49a6-8655-17f19fd14232.png)
![2022-05-10_19-08](https://user-images.githubusercontent.com/754494/167684585-d282e723-61be-49e3-9a58-4f0811705b19.png)

**Comment by jdorn** [comment]
I'm able to reproduce it.  Should be an easy fix

**Comment by andehen** [comment]
Thanks for the quick fix! :raised_hands:
