### ISSUE TITLE
[Bug] Filter by tags on metrics is limited 

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#3460]
When on the metric page, the only options in the tag dropdown are the ones that happen to be applied to metrics on the current page. If there are multiple pages of metrics, the tags applied to these metrics are not available for filtering. Allowing to choose from all tags regardless of if they have metrics tagged with them is probably the best solution.

**Comment by ansh-kaushik** [comment]
can u provide more informaton to replicate the issue
