### ISSUE TITLE
[Feature] Experiment Analysis : End date

### ISSUE THREAD

**Issue by natasha-growthbook** [growthbook/growthbook#3477]
### Description of Feature

It would be really helpful to have a checkbox not only for "Current datetime" but also for "Experiment end":

![image](https://github.com/user-attachments/assets/b89f4410-32ca-4ad9-bc14-c98ecf5e03fc)

**Comment by and-kul** [comment]
Checkbox with "experiment end" for the right bound should be visible only for already finished experiments

Moreover, I think it should be the default behavior for additional analysis reports for finished experiments

**Comment by lukesonnet** [comment]
> Checkbox with "experiment end" for the right bound should be visible only for already finished experiments
>
> Moreover, I think it should be the default behavior for additional analysis reports for finished experiments

Agreed.
