### ISSUE TITLE
[Bug] Ad hoc report analysis timezone discrepancy

### ISSUE THREAD

**Issue by natasha-growthbook** [growthbook/growthbook#3478]
### Summary

When creating an ad hoc report the analysis settings experiment start date defaults to local time and not UTC causing timezone discrepancy.

#### Expected Behavior

When creating an ad hoc report the timezone should default to UTC and be the same timezone value as the original report.

#### Current Behavior

When creating an ad hoc report the timezone defaults to the local timezone instead of UTC to match the original report

https://github.com/user-attachments/assets/09051668-2f41-4cd5-8e78-588f283eb7f1

**Comment by natasha-growthbook** [comment]
Also the end date/time of the experiment was June 27th 2023 in the original report, but creating the ad hoc report the end date defaults to "today" instead of the experiment end date of the original report for the stopped experiment.

**Comment by lukesonnet** [comment]
Closed by #3482
