### ISSUE TITLE
que: Does this work with React SSR?

### ISSUE THREAD

**Issue by apatel369** [growthbook/growthbook#349]
Does growthbook a/b testing with React server side rendering? 

I found client side rendering example using CSR but couldn't find anything about SSR.
https://dev.to/jdorn/ab-testing-with-create-react-app-53fg

Also docs don't mention anything about it.
https://docs.growthbook.io/lib/react

**Comment by jdorn** [comment]
We have an example on Next.js using SRR, CSR, and a hybrid approach. https://github.com/growthbook/examples/tree/main/next-js
