### ISSUE TITLE
Add "owners" to metrics, dimensions, segments, and features

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#356]
Ability to specify an owner (or point of contact) for various objects - metrics, dimensions, segments, and features.  Experiments and reports already have owners.

The person who first creates the object should be marked as the owner.  In the future, we can add the ability to change the owner, but that's not required for this initial version.

**Comment by kelvanb97** [comment]
https://github.com/growthbook/growthbook/pull/407
