### ISSUE TITLE
Download experiment results as CSV / JSON

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#357]
On experiment/report results, add the ability to download everything as CSV/JSON.  This can be done entirely on the front-end without any API calls since all the data is available on the page already.

The resulting CSV/JSON should have similar columns to the results table.

Once you build the CSV/JSON string on the front-end, you can create a file Blob and trigger the download in the browser.

**Comment by mknowlton89** [comment]
After discussing this with @jdorn at standup on 6/23, we are going to move forward with just the CSV export, not the JSON export.
