### ISSUE TITLE
Heap integration with growthbook

### ISSUE THREAD

**Issue by Omid2203** [growthbook/growthbook#367]
Hi. This is Omid, product manager at a marketplace. We are working with Heap to analyze our data and customer behavior. Since last week we've been using Growthbook to run A/B testing in our app. As I see, you integrated Mixpanel with Growthbook. I want to ask you to give this opportunity to us and connect Heap with Growthbook.

**Comment by jdorn** [comment]
Hi.  To use Heap with GrowthBook, we recommend setting up Heap Connect (https://help.heap.io/category/heap-connect/) to sync your data into a SQL warehouse such as Redshift.  As far as I know, Heap doesn't offer the same flexibility as Mixpanel when it comes to querying data via an API, so it's much harder (if not impossible) for us to build a direct integration.
