### ISSUE TITLE
Store assets in object storage

### ISSUE THREAD

**Issue by matclayton** [growthbook/growthbook#37]
We are evaluating GrowthBook right now, and it looks fantastic.

It would be great to see support for image storage in systems such as Google Storage or S3 to reduce the amount of infrastructure needed to support GrowthBook. 

Maybe this could be via a plugin system to allow multiple different options.

**Comment by jdorn** [comment]
The cloud version of Growth Book is actually already using S3, so the bulk of the code is there already.  Enabling that for self-hosted installations should be relatively easy.

**Comment by matclayton** [comment]
Amazing :) Also whilst I'm making suggestions. Not using MongoDB, and using some SQL based store for metadata would also be a really nice win. We have these around already and fully managed/backed up, adding MongoDB to list of DB's to manage and operate is a nasty increase in complexity operationally.

**Comment by jdorn** [comment]
S3 support is now enabled.  There are a few new environment variables you need to set to enable it.  https://docs.growthbook.io/self-host

```ini
UPLOAD_METHOD=s3
S3_BUCKET=my-bucket
S3_REGION=us-east-1
S3_DOMAIN=https://my-bucket.s3.amazonaws.com/
AWS_ACCESS_KEY_ID=blah #not required if deploying to AWS with an instance role
AWS_SECRET_ACCESS_KEY=blah #not required if deploying to AWS with an instance role
 ```

**Comment by matclayton** [comment]
Amazing!
