### ISSUE TITLE
Show better error message when someone forgets to set API_HOST or APP_ORIGIN

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#381]
Currently, we show the same `Failed to fetch` message for all network errors when running GrowthBook.

There is one common situation that we can detect and show better error messages for: when the user deploys GrowthBook to a custom domain (not localhost), but forgets to update the environment variables `APP_ORIGIN` and/or `API_HOST` to match.

**Comment by kelvanb97** [comment]
https://github.com/growthbook/growthbook/pull/392
