### ISSUE TITLE
Show metric description/details on hover on experiment result page

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#389]
In the experiment result table, metric names link to the metric detail page.  A lot of times someone just wants to quickly see more details about the metric and making them constantly go back and forth between pages is annoying.

We can add a tooltip with details when they hover over the metric link.  Specifically, we should show the following:
- The description (if any)
- The type (binomial, count, etc.)
- Tags (if any)
- If there's a cap, what the cap is set to
- The conversion window settings

For inspiration, this is what GitHub does when you hover over an issue number - 

![Image](https://user-images.githubusercontent.com/1087514/173695184-4b09fa52-2ab5-4ee3-ad9f-2bc3eff0c1b9.png)

**Comment by kelvanb97** [comment]
https://github.com/growthbook/growthbook/pull/417
