### ISSUE TITLE
Simplify data source query settings form UI

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#390]
This page is where users go to set up and configure their data source:

![image](https://user-images.githubusercontent.com/1087514/190491696-82b17d6a-e66f-4723-a5e7-c4c10f94ffc4.png)

The different sections of that page are:
- Identifier Types
- Experiment Assignment Queries
- Identifier Join Tables (only shows up if you add one, missing from the above screenshot)
- Jupyter Notebook Query Runner

In order to change any of the sections, there is a single monolithic popup form, which is a terrible UX:

![Image](https://user-images.githubusercontent.com/1087514/173696206-32e74f29-d06f-4633-b26c-08fd0923a087.png)

It would be much better if each of those sections had their own dedicated CRUD actions.  For example, you should be able to quickly add a new Identifier Type or edit one of your Experiment Assignment Queries.

In addition to the UI, this may also require adding new API endpoints as needed.

## Sections

- [x] Identifier Types
- [ ] Experiment Assignment queries
- [x] Identifier Join tables
- [x] Jupyter Notebook query
- [ ] header changes and deprecation of old form

**Comment by tinahollygb** [comment]
The PR that addresses the Jupyter Notebook changes is here: https://github.com/growthbook/growthbook/pull/527

**Comment by tinahollygb** [comment]
The PR for the Identity Types section is here: https://github.com/growthbook/growthbook/pull/534

**Comment by tinahollygb** [comment]
PR for Identifier Join tables here: https://github.com/growthbook/growthbook/pull/539

**Comment by tinahollygb** [comment]
The PR for the Experiment Assignment (exposure) queries is here: https://github.com/growthbook/growthbook/pull/550
