### ISSUE TITLE
Date dimension double counts users who view an experiment on multiple days

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#412]
We generate the following SQL for the date dimension:

```sql
__distinctUsers as (
  -- One row per user/dimension
  SELECT
    e.anonymous_id,
    format_date("%F", date_trunc(e.conversion_start, DAY)) as dimension,
    ...
  FROM
    __experiment e
  GROUP BY
    dimension,
    e.anonymous_id
),
```

This means each day the user views an experiment, they will be counted as a unique user.  Instead, we want to just count the user once and use their earliest timestamp to determine the dimension value.

So something like this instead:

```sql
__distinctUsers as (
  -- One row per user/dimension
  SELECT
    e.anonymous_id,
    format_date("%F", date_trunc(MIN(e.conversion_start), DAY)) as dimension,
    ...
  FROM
    __experiment e
  GROUP BY
    e.anonymous_id
),
```

It's up for debate if this should be the behavior for all dimensions or just date.  For something like `browser`, if someone uses both chrome and safari, do we just pick one for the user or include them in both?

For now, let's just fix the date dimension and then worry about the others later.

**Comment by lukesonnet** [comment]
This behavior was changed by #1066 so that we only ever get one row per `date exposed` or other dimension.
