### ISSUE TITLE
Support SSL for Trino

### ISSUE THREAD

**Issue by emiel-veersma** [growthbook/growthbook#413]
As discussed on Slack, I'd like to connect with our MSSQL database through Trino (since MSSQL is not supported). When I try to connect from Growthbook with Trino, I get the following error. It looks like SSH is not supported for Trino.

![image](https://user-images.githubusercontent.com/57494721/175967601-f16ce2b0-fbbe-4c50-bb4b-6c90860f4597.png)

**Comment by jdorn** [comment]
We added support for SSL connections to Postgres.  I think Presto/Trino would be very similar.  This is the UI we used for Postgres - 
![image](https://user-images.githubusercontent.com/1087514/184123107-5de661a1-098b-45fd-9cad-e6ee6264d67a.png)

![image](https://user-images.githubusercontent.com/1087514/184123178-e8924423-12e6-411e-bff3-37a37412e1b6.png)
