### ISSUE TITLE
Ability to change the role for a pending invite

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#414]
We let admins change a user's role after they accept an invite, but not while it's still pending.  Currently, the only solutions for admins is to either wait until the invite is accepted to change the role or delete the invite and create a new one with a new link, both of which are kind of annoying.

**Comment by reecenil** [comment]
@jdorn , I am trying to working on issue. Is the screenshot below already OK? Let me know.. Thanks!
![image](https://user-images.githubusercontent.com/89799294/184119717-feeb49ad-2ce0-4f33-88ce-b64c03dcd76f.png)

**Comment by jdorn** [comment]
We might want to change that to be a drop-down menu now that there are 3 different actions.  If you look in `MemberList.tsx`, you can see an example of that:

```tsx
  <MoreMenu id="invite-list">
    <button className="dropdown-item" ...>...</button>
    <button className="dropdown-item" ...>...</button>
    <button className="dropdown-item" ...>...</button>
  </MoreMenu>
```

**Comment by reecenil** [comment]
Thanks! I'll pattern it there

**Comment by reecenil** [comment]
#473
