### ISSUE TITLE
Rules are only applied to environments that are on when a feature is created

### ISSUE THREAD

**Issue by B1ll1** [growthbook/growthbook#418]
I do not quite understand why it is like this but it would be really nice if when we are creating a feature, the rules you define get applied to all environments regardless if they are on or off.

We usually start our tests with only dev environment on and then we need to go and add the same rule again for each of the other environments. And start with all of them on just to get the rule so then turn it off also seems unnecessary.

**Comment by Auz** [comment]
https://github.com/growthbook/growthbook/blob/main/packages/front-end/components/Features/FeatureModal.tsx#L114

**Comment by jdorn** [comment]
I agree, it doesn't make sense to only add rules to enabled environments.  The current behavior also causes the app to crash when there's no `dev` environment.

I think a quick fix that adds the rule to all environments could work.  Maybe longer term, we can add checkboxes where you can choose which envs you want the rule to be applied to (and default to having them all checked).

**Comment by B1ll1** [comment]
@jdorn this would be awesome
