### ISSUE TITLE
Failed to install with yarn on OS X Big Sur

### ISSUE THREAD

**Issue by aptlin** [growthbook/growthbook#42]
Running `yarn` on a clean clone of the repo fails with the following error after fetching all packages:

```bash
error https://registry.yarnpkg.com/rehype-add-classes/-/rehype-add-classes-1.0.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "EPERM: operation not permitted, open '/Users/sdll/Library/Caches/Yarn/v6/npm-rehype-add-classes-1.0.0-3d8b37b13ce06e2eb8681b33ccf1c2995611a33b-integrity/node_modules/rehype-add-classes/test.js'"
```
Trying out `yarn install --network-concurrency 1` and `yarn cache clean`  and `rm -rf ./yarn.lock && yarn` did not help, all suggested here:

https://github.com/yarnpkg/yarn/issues/6312

This issue suggests that the error is related to the prebuild script of `rehype-add-classes`:

https://github.com/yarnpkg/yarn/issues/7212#issuecomment-493720324

## Environment
* `node --version`: v14.17.5
* `yarn --version`: 1.22.11
*  `system_profiler SPSoftwareDataType`
    - System Version: macOS 11.5.1 (20G80)
    - Kernel Version: Darwin 20.6.0
 
<img width="1772" alt="Screen Shot 2021-08-13 at 12 43 32" src="https://user-images.githubusercontent.com/17913919/129338353-e7235068-9d48-4c95-b5cc-cb253b63c94d.png">

**Comment by jdorn** [comment]
I'm not able to reproduce.  If you remove the `rehype-add-classes` dependency from `packages/docs/package.json` does that fix the problem?

**Comment by aptlin** [comment]
It did, thanks! You might need to run `yarn cache clean` to reproduce this

Have you considered using npm instead of yarn (npm did not have problems with installation with npm install --force)?

**Comment by jdorn** [comment]
Ok, I'll remove that dependency.  Looks like it's only used one place and can be replaced by a couple lines of code.

We are currently using yarn workspaces pretty heavily, so switching to npm is not trivial.

**Comment by aptlin** [comment]
Thanks! Just out of interest, do they differ much from the npm workspaces?
https://ruanmartinelli.com/posts/npm-7-workspaces-1

**Comment by jdorn** [comment]
Thanks for the link!  I haven't followed npm for a while and didn't know they added workspaces recently
