### ISSUE TITLE
Sort list of projects alphabetically

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#425]
If you add multiple projects in GrowthBook, the dropdown list in the left navigation is sorted by creation date.  We should instead sort them alphabetically.  The dropdown is rendered in `packages/front-end/components/Layout/ProjectSelector.tsx`

**Comment by phershbe** [comment]
@jdorn I was actually confused about the local development environment before, I had it setup using the basic Docker build which obviously doesn't allow you to edit the code, then I had trouble with setting it up following the contributing guide. I got on to the Slack workspace and Graham welcomed me and I mentioned the issue and he said to message you on there.
