### ISSUE TITLE
Update Node.js version in Dockerfile

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#426]
We're currently using Node.js 14.  It's still receiving security updates, but we should update to Node.js 16 or 18 soon anyway to stay on top of things.

In addition, there have been reports that our Javascript SDK does not work on Node.js 18 and Typescript, so this may help us test and fix that as well.

**Comment by mrienstra** [comment]
More detail here: https://www.linen.dev/s/growthbookusers/t/541440/JFYI-there-are-many-high-amp-critical-CVEs-in-prod-found-in-
