### ISSUE TITLE
Customizable info icons / descriptions in form sections

### ISSUE THREAD

**Issue by xgumara** [growthbook/growthbook#430]
We want to add some governance on how features, experiments and metrics are named and used but we find it problematic having to explain "the rules" outside of GrowthBook.

As admins of GrowthBook in our org, it would be nice to add short custom descriptions in each part of a form. This will be used to explain how to name things, or which tags to use where.

This could be enabled as an advanced feature that can be turned on by admins if relevant. One option could be to add an info icon next to the title of the section that shows the customized text when you hover into it. Another one would be to simply add a description after the title of the section.

**Comment by hildeirin** [comment]
Would be great to also be able to rename tags like we can for projects! 🙏🏼
