### ISSUE TITLE
React Native - error Failed to load configuration of your project

### ISSUE THREAD

**Issue by mickeyhead7** [growthbook/growthbook#433]
When running a react-native app, Metro will not build due to an error when processing @growthbook/growthbook-react:

```bash
error Failed to load configuration of your project.
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in...
```

Technically, this may be a react-native issue ([see here](https://github.com/facebook/react-native/issues/28710)), but can be easily resolved by updating the exports set in `package.json` of this package.

The problem is that the package.json file is not being recognised as exported if explicitly excluded from the `exports` section of the package.json file, hence it can't be found by the Metro bundler. The issue also does not occur if there is no `exports` section in the package.json file.

I believe it makes sense to update this package, to retain its compatibility with react-native, and likely other projects, while retaining the existing exports.

```json
"exports": {
  "./package.json": "./package.json",
  ".": {
    "require": "./dist/cjs/index.js",
    "import": "./dist/esm/index.js"
  }
},
```

Other packages have implemented this solution. ([see here](https://github.com/d3/d3/pull/3576/files)).

**Comment by RashedRahimi** [comment]
where we must use this codes?

**Comment by tinahollygb** [comment]
Is this still a problem?

We have an example React Native project that works here: https://github.com/growthbook/examples/tree/main/react-native-cli

**Comment by jdorn** [comment]
Closing this issue. If this is still a problem, please create a new one
