### ISSUE TITLE
Ability to pass attributes to the SDK when a feature is checked for on/off

### ISSUE THREAD

**Issue by DNAlchemist** [growthbook/growthbook#437]
If a rest service is on the backend, it will serve many users with different attributes.
Attributes can be taken from headers or some other parameters.
Now to change attributes, you need to completely reinitialize the SDK.
Perhaps it makes sense to make a separate interface for working with multiple users and pass attributes as a method parameter.

For example, I developed a _release feature_. 
When enabled it sends the data to the audit.
And I want to enable this feature only for a certain group of users (like my teammates)

**Comment by DNAlchemist** [comment]
Guys? Maybe something is not clear and I should clarify the question?

**Comment by DNAlchemist** [comment]
<img width="992" alt="Screenshot 2022-08-19 at 10 38 20" src="https://user-images.githubusercontent.com/6822421/185538062-fadbc98b-0933-495d-84fd-9e197662f746.png">

**Comment by jdorn** [comment]
The recommended approach is to create a new SDK instance for every request to keep attributes isolated
