### ISSUE TITLE
Removing/rotating API keys

### ISSUE THREAD

**Issue by sebastian** [growthbook/growthbook#438]
Is it possible to remove/invalidate/rotate API keys? I cannot find a way to do it in the Growthbook interface at present nor have I been able to locate any way of doing this from the docs.

A use-case for this would be if:
- you decommission a service that had a key (and use separate keys by service)
- you accidentally share a key with a wider audience than intended and want to change/update it

**Comment by xgumara** [comment]
Just to add to this, it seems that we can only delete the top two API keys from the list.

**Comment by sebastian** [comment]
Here is a screenshot of what we are seeing:

![Screenshot 2022-07-12 at 13 30 48@2x](https://user-images.githubusercontent.com/1089/178480637-71335dd3-cf4b-4113-afc1-95ab9e15b064.png)

(running build: [9eb4a3f](https://github.com/growthbook/growthbook/commit/9eb4a3ff8d1ef6a889ba27b21bfc52befe0a9684) (2022-06-29))

**Comment by jdorn** [comment]
We require at least one API key per environment to exist. So if you create a new key first, you'll be able to delete the old one. We should make this more clear in the UI.
