### ISSUE TITLE
How to setup DataSourceSettings for BigQuery

### ISSUE THREAD

**Issue by aviggiano** [growthbook/growthbook#45]
Hi there. First of all, this project is awesome. Kudos to you all!

I have a question: is there a way through the UI to setup the `DataSourceSettings` that are used so that I don't need to change the default SQL queries? 

After reading the source code it seems there is an option to change the column names instead of rewriting the SQL statement, but I can't find out how.

Thanks

**Comment by jdorn** [comment]
We originally had sort of a query builder where you specify the table and column names, but switched to raw SQL input to make things more straight forward and flexible. So what you're seeing in the code is a legacy holdover from that earlier UI and not really supported anymore.

I'm curious about your use case though. Are there specific reasons you prefer a query builder UI vs raw SQL?

**Comment by aviggiano** [comment]
Got it.

Well, the thing is: the documentation on [Data Sources](https://docs.growthbook.io/app/datasources) isn't very clear, so I'm not sure about how to structure my data. In particular, the SQL queries exemplified refer to three tables (`experiment_viewed`, `identifies`, and `pages`) that aren't mentioned in any other place. 

In my case, I already have a BigQuery (denormalized) table with some metrics (for example, `impression`, `click`, `like`, `dislike`, etc.) with lots of dimensions (`user_agent`, `device_type`, ...), and I wish to use the same dataset for my A/B tests, but analyze the data on growthbook.io instead of using Data Studios, since all the statistics/inference analysis are already taken care of. 

If I understand correctly, I'll probably need to add two columns (`experiment_id`, `variation_id`) and then figure out how to translate the SELECT statements Growth Book expect. 

-- But what exactly are those? I think the docs assume you have 3 tables, but not all data warehouses are structured like that. Maybe adding a sample dataset would help.

**Comment by jdorn** [comment]
I agree the documentation around data sources is not great yet.  I can try and explain it a little better here.  To use growth book, only one additional table is required from what you have now - one which tracks which user_id saw which variation in an experiment. So for example:

user_id | experiment_id | variation_id | timestamp
-----------|--------------------|------------------|----
1 | button-test | 0 | 2021-08-17 00:00:00
2 | button-test | 1 | 2021-08-17 00:01:00

The experiment query would then be something like this:

```sql
SELECT
  user_id,
  experiment_id,
  variation_id,
  timestamp,
  '' as url, -- optional - the url the user was on when put into the experiment
  '' as user_agent -- optional - used for drilling down by browser/device
FROM
  experiment_viewed
```

The other two queries for a data source are entirely optional and enable advanced use cases.  The page views query, if set, can be used to predict running times of experiments before you start by analyzing historical traffic.  The identifies query, if set, can enable experimenting on both logged-in users and anonymous visitors.

Your other existing tables - `impression`, `click`, etc. would each be a separate metric and have it's own SQL query.  For example:

```sql
SELECT
  user_id,
  timestamp
FROM
  click
```

Once those are building blocks are defined, our query engine can combine them into more complex SELECT statements, pass the SQL on to BigQuery, run the resulting data through our stats engine, and show the analysis.

**Comment by aviggiano** [comment]
Hey,

Thanks for the detailed information.
I'm still trying to figure out the SELECT queries, so I have a couple of questions: 

1. The `experiment_viewed` table name is a placeholder, right? I can name it whatever I want, I assume? For example, here's my BigQuery table

<img width="536" alt="Screen Shot 2021-08-19 at 08 45 28" src="https://user-images.githubusercontent.com/3029017/130063163-e95149d1-5269-4f96-aa57-c0564b5d769f.png">

So in this case, should I use that exact format when replacing the `Experiments SQL`?

![screenshot-2021-08-19-08-47-15](https://user-images.githubusercontent.com/3029017/130063421-7c4ace62-a298-455c-bd5c-5f89d27596dc.png)

If so, I get an error when trying to analyze the results

![screenshot-2021-08-19-08-46-23](https://user-images.githubusercontent.com/3029017/130063292-83ff458a-de8b-4cd0-b327-dfa1a1a3932f.png)

2. Also, about the metrics query, on BigQuery I have a single table and I am performing the following statement:

<img width="538" alt="Screen Shot 2021-08-19 at 08 49 12" src="https://user-images.githubusercontent.com/3029017/130063617-26339d39-6cc4-4cc6-b250-bd10a36b7355.png">

But if I use that same query on Growth Book, I get an error, I guess it expects a `page` table

![screenshot-2021-08-19-08-49-57](https://user-images.githubusercontent.com/3029017/130063746-2a4af5b7-991a-436f-a2d9-f03eb9421fb1.png)

Should the table names match exactly what Growth Book expects (`experiment_viewed`, `page`, `identifies`)? Can I still use it with a denormalized table, like mine?

**Comment by jdorn** [comment]
1.  You can use whatever table name you want in the query.  `experiment_viewed` is just a placeholder.  I just fixed the `Cannot read property '0' of null` bug yesterday so that query should work now.

2.  For a binomial metric, the query needs to return only 3 columns: `user_id`, `anonymous_id` and `timestamp`.  If at least one row returns for a user, they will count as "converted", otherwise they won't. If you have all of your events in a single table, you can filter it down to only the events you want to include using a WHERE clause.  Something like:
    ```sql
    SELECT 
      user_id, 
      client_id as anonymous_id, 
      timestamp 
    FROM `r2u-analytics.r2u.sdk-events` 
    WHERE event = 'like'
    ```

The error about `pages` is because your data source settings is still using the default Pageviews query.  Based on the screenshot you added, I would define the 3 data source queries as:

### Experiments SQL
What you have already looks good

### Users Query

This will return lots of duplicate rows, but that should be fine.  You can add a GROUP BY or DISTINCT clause if you want.
```sql
SELECT user_id, client_id as anonymous_id FROM `r2u-analytics.r2u.sdk-events`
```

### Pageviews Query
If you have a specific event for "page view", you can add a WHERE clause, but otherwise it should work fine by just returning all events.
```sql
SELECT
  user_id,
  client_id as anonymous_id,
  timestamp,
  url,
  user_agent
FROM 
  `r2u-analytics.r2u.sdk-events`
```

**Comment by aviggiano** [comment]
Thanks for the great explanation.
Now it's clear how the data sources integration work. And about your first question: Being able to see the raw SQL and reproduce it on my end is perfect for debugging porposes.
I'll close this issue.
Best

**Comment by jdorn** [comment]
Thanks for your patience and working through this with me!  Based on our discussion I reworked the documentation for [data sources](https://docs.growthbook.io/app/datasources) and [metrics](https://docs.growthbook.io/app/metrics) so hopefully it will be clearer now.
