### ISSUE TITLE
Support case-sensitive (upper-case) feature names

### ISSUE THREAD

**Issue by valeriyo** [growthbook/growthbook#457]
I added a feature named "showSecretUI" and after saving it, the name turned into "showsecretui" -- not good. There is nothing indicating that lower-casing would happen:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/7052801/181344566-8c5e46bc-e6e6-4629-8f0e-c673951a2ac2.png">

Please preserve the case of feature names, and don't just lower-case them.

**Comment by parth-ganatra** [comment]
Needed the same functionality for my use case. Will the above change break any existing features?
