### ISSUE TITLE
Include variation name in API & webhook payload + support in SDK

### ISSUE THREAD

**Issue by andehen** [growthbook/growthbook#463]
Currently, the only data about variations that is exposed is the list of variation _values_. In the SDK's, the position in the list is exposed in a `variationId` variable. Using the `variationId` is recommended in tracking. However, only having `variationId` (0, 1, 2, ..) in the event data is not sufficient for an analyst to understand the data in it self. One would have to look up in Growthbook to see what name a variation have (ex. control, treatment, etc).

It would be nice to also have the _variation name_  (that can be set in the Growthbook UI) available in the payload & SDK such that this can be used to populate the tracking payload. It will make analysis of the raw data more convenient.

**Comment by jdorn** [comment]
This is supported in the latest GrowthBook version
