### ISSUE TITLE
Check if user is in experiment/variation without tracking

### ISSUE THREAD

**Issue by zahnrodolfo** [growthbook/growthbook#477]
It would be nice to have a function in the library that supports checking if an user is in an experiment/variation that does not add him to the experiment in case he is not. I already had some situations that I needed that and this is what I implemented. We use the value to check for which variation but it could also be done with the variation itself.

```
public isVariationWithoutTracking(experimentName: string, variation: number) {
    const result = this.growthbook.getAllResults().get(experimentName)?.result;
    return result?.inExperiment && result?.value === variation;
  }
```

**Comment by jdorn** [comment]
We recommend using an activation metric for this use case.  This behavior often leads to bugs and data quality issues, so it's best to always track and filter out later during analysis if required.
