### ISSUE TITLE
Ability to run direct SQL queries for metrics 

### ISSUE THREAD

**Issue by evaldask** [growthbook/growthbook#480]
Hello, I would like to request a feature where you are able to run direct SQL queries for metric computation. An example query:
```SQL
SELECT variant_id, sum(event_value) as value, count(*) as total FROM metrics_table
WHERE experiment_id='{{ experimentId }}' AND timestamp BETWEEN '{{ startDate }}' AND '{{ endDate }}'
GROUP BY variant_id
```
Or maybe this is already doable in growthbook?

**Comment by judahrand** [comment]
This is already doable if you make your `value` and `total` two different Metrics, I believe.

**Comment by lukesonnet** [comment]
Sorry for the delayed response. This is a bit unclear, but you can use SQL directly and the User Value Aggregation field to create a variety of metrics. Feel free to follow-up if you need help creating a particular metric.
