### ISSUE TITLE
Allow bigger editor fo SQL Queries in Experiment setup

### ISSUE THREAD

**Issue by lgabs** [growthbook/growthbook#497]
I'd like to make a suggestion: allow a bigger editor when writting an SQL Query in experiment's setup. This can help user to see it more clearly.
![suggestion-growthbook](https://user-images.githubusercontent.com/27077298/188695469-89d06a96-9484-4256-843d-55cdc8b53778.png)

**Comment by lgabs** [comment]
Indeed, I realized that after going through that window, the next window has a bigger view where I can check the query more clealy. That could happen in the previous step maybe, where the user will spend time checking it before proceding.

![image](https://user-images.githubusercontent.com/27077298/188704327-babe625e-a43c-49db-979b-24d88f891a04.png)

**Comment by lukesonnet** [comment]
The SQL edit field has changed much since this issue was opened, and in most places it is considerably larger. Closing.
