### ISSUE TITLE
SQL connections with SSL Enabled

### ISSUE THREAD

**Issue by afranzi** [growthbook/growthbook#50]
Hi there,

It would be great if you could add the option of enforcing an SSL connection on the SQL connectors.

 Otherwise, we cannot use it, since our Redshift enforces the SSL to be enabled for security reasons.

**Comment by jdorn** [comment]
Just added an option to enable SSL for redshift connections.  Will take about 10 minutes to rebuild and push an updated docker container.

**Comment by dima-tpf** [comment]
Validated that it's working to connect with Redshift with SSL enabled requirement
