### ISSUE TITLE
sdk-js/package.json: "type": "module"

### ISSUE THREAD

**Issue by mrienstra** [growthbook/growthbook#509]
As per: https://www.linen.dev/s/growthbookusers/t/442993/Hi-guys-I-m-having-some-package-module-issues-using-the-SDK-

>When adding “type” : “module” I still got errors
>
>```
>node:internal/errors:466
>  ErrorCaptureStackTrace(err);
>  ^
>
>Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/xxx/node_modules/@growthbook/growthbook/dist/esm/GrowthBook' imported from /Users/xxx/node_modules/@growthbook/growthbook/dist/esm/index.js
>```
>
>However, when I started checking that code, I saw that `.js` was missing from the import path in the following places:
>
>`node_modules/@growthbook/growthbook/dist/esm/index.js` -> missing in `export { GrowthBook } from "./GrowthBook";`
>`node_modules/@growthbook/growthbook/dist/esm/GrowthBook.js` -> missing in `util` and `mongrule` import
>
>By adding .js to those three places (combined with adding `"type" : "module"` to package.json) it started up just fine!

Took a quick look at [packages/sdk-js](https://github.com/growthbook/growthbook/tree/b9232c4/packages/sdk-js) & [the history for packages/sdk-js](https://github.com/growthbook/growthbook/commits/b9232c4/packages/sdk-js) and it looks like these changes haven't landed yet, also checked PRs and didn't see one that looked like a match.

**Comment by nova-script** [comment]
wow, this still unsolved.

**Comment by jessezhang91** [comment]
if i'm correct, an alternative solution here is to change the file extensions of everything under `esm` to `.mjs` (and update `package.json` accordingly)

for now, i'm working around this by using `patch-package` and removing the `exports` from `package.json` to make it fall back to the `cjs` exports and that seems to be working.

**Comment by august-growthbook** [comment]
Hi Ken, I heard back from the Engineering team and they will need to do some testing to make sure this change will work in all of the different JavaScript runtimes and versions that we support.

Thanks again for submitting the PR!

**Comment by elledienne** [comment]
Is there any update on this issue or a workaround to unblock all the users that need `esm`?

**Comment by mrienstra** [comment]
Huzzah, congrats @ken-browning, @jdorn & @bttf, well done! 🎉❤️
