### ISSUE TITLE
[Enhancement] Importing past experiments has settings for date, min duration, and min users which are not exposed to users

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#548]
### Summary

When you import past experiments, it is not clear to users that some filters are applied to the SQL query. We add a min 6 day duration, date range, and min number of users. This may cause some tests to not import, or for sample tests to not show up. We should expose these settings to the user and let them adjust them (in the front end or in SQL).

**Comment by jdorn** [comment]
To fix, we can
1. Remove these filters from the SQL and implement in JavaScript on the front end instead
2. Show toggles in the UI to turn specific filters on or off
3. Allow the user to modify the default filter values (we do this for min experiment length already)
