### ISSUE TITLE
[Feature] Support a Dark Mode theme

### ISSUE THREAD

**Issue by tinahollygb** [growthbook/growthbook#574]
### Description of Feature

Add support for dark mode.

- [ ] Allow the user to choose the theme (find somewhere in the UI to put a toggle)
- [ ] Detect the user's preference

**Comment by Bishwas-py** [comment]
Yeah, dark mode isn't performing well in sveltekit tailwind css.
When I change `prefers-color-scheme: dark` from inpect tool, it work perfectly, but when I do by changing `tailwind.config.cjs` ...
```
darkMode: 'class',
```
and 
```
document.documentElement.classList.toggle('dark');
```
only few parts get toggled and many other are just in light mode.
