### ISSUE TITLE
[Bug] Ratio metric square root of a negative number

### ISSUE THREAD

**Issue by judahrand** [growthbook/growthbook#605]
### Summary

When using a Ratio metric I encounter an error message:

`Argument to SQRT cannot be negative: -1.38778e-17`

in the generated SQL 

#### Expected Behavior

No error

#### Current Behavior

Error

**Comment by jdorn** [comment]
@judahrand Are you able to see what the result of the query is at the `__stats` CTE?  The `sqrt` doesn't happen until the final query, so if you replace that with `SELECT * FROM __stats`  you should get back all of the raw mean, stddev, etc. from the variations.

I think I have a fix, but it would be good to verify against some real input data to make sure.
