### ISSUE TITLE
[Bug] Markdown not rendered in Metric tooltips

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#631]
### Summary

In the experiment results table, we show a tooltip when hovering over metric names.  The tooltip gives a summary view of the metric, but it doesn't render markdown properly in the description.

To fix, in `packages/front-end/components/Metrics/MetricTooltipBody.tsx`, we currently display the description as plain text and truncate it after 300 characters.  Instead, we should render it using the `<Markdown>` component and set a max-height with `overflow-y: auto` so it scrolls if it's too long.

**Comment by mknowlton89** [comment]
@jdorn Does it make sense to have a scroll within a `Tooltip` component since it will automatically close `onMouseLeave` or `onPointerLeave`?
