### ISSUE TITLE
[enhancement] Improve metric UI for adding SQL

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#662]
Right the UI for the user to switch between the raw SQL and query builder are radio buttons.  

<img width="778" alt="Screen Shot 2022-10-24 at 12 32 36 AM" src="https://user-images.githubusercontent.com/46107/197471725-d3b9f62a-acaa-41e5-a777-d1d00e1f8294.png">

Using tabs would make this a better UI as this state is not a form value.

**Comment by Auz** [comment]
![Image](https://user-images.githubusercontent.com/46107/199643637-638bb029-4a38-4fad-9579-409f907516bc.png)
![Image](https://user-images.githubusercontent.com/46107/199643638-d05fc307-bb3a-45ac-a06f-e719fdead8be.png)

**Comment by jdorn** [comment]
With the new Metric Fact Tables, this is no longer necessary
