### ISSUE TITLE
[Feature] Grant access per project for different users

### ISSUE THREAD

**Issue by tommy04062019** [growthbook/growthbook#667]
### Description of Feature

In an organization, there are many developer teams. We should give access to only members that have control on their project

**Comment by Auz** [comment]
Hi Tommy - we have #659, will that solve your issue?

**Comment by jdorn** [comment]
This was fixed in #659

**Comment by tommy04062019** [comment]
> Hi Tommy - we have #659 coming soon, will that solve your issue?

It seems ok but not fit to me, it's only for commercial version, I found another solution already. BTW, thanks so much
