### ISSUE TITLE
Import saved groups from mixpanel cohorts.[Feature] 

### ISSUE THREAD

**Issue by VardanAggarwal** [growthbook/growthbook#669]
### Description of Feature

Currently, we allow users to manually create saved groups to target feature flags. This can be improved if we allow updating saved groups from data sources, specifically Mixpanel.
* Mixpanel has a functionality where they export cohorts to various [integrations](https://help.mixpanel.com/hc/en-us/sections/115001517666-Cohort-Sync-Integrations) & can be synced using [Webhooks](https://developer.mixpanel.com/docs/cohort-webhooks).
* This sync can be used to create & update saved groups on a regular basis.

**Comment by jdorn** [comment]
We have REST API endpoints now to update saved groups, so this should be possible today.  https://docs.growthbook.io/api#tag/saved-groups
