### ISSUE TITLE
[Bug] Chart data points do not match up with graph

### ISSUE THREAD

**Issue by jbean96** [growthbook/growthbook#671]
### Summary

When hovering over the chart for a metric, the data points do not seem to match up with the graph (it's like the data points of of the graph are graphed on a different scale than the actual line).

#### Expected Behavior

When hovering over the graph, the data point revealed is for the corresponding section of the graph which I am hovering over. 

#### Current Behavior

<img width="810" alt="image" src="https://user-images.githubusercontent.com/22803097/198152945-e8dcceee-f833-44c5-ac7d-fdca3bbc9595.png">

**Comment by lukesonnet** [comment]
I believe this behavior was resolved by #1060
