### ISSUE TITLE
[Feature] Support Semver targeting conditions

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#672]
### Description of Feature

It's currently difficult to target features based on a Semver attribute in GrowthBook.  Greater than and less than don't work as expected since it performs a string comparison (e.g. `2.10.0` is "greater than" `10.2.0`).

If the semver sections had leading zeros for padding (e.g. `001.002.003`), that would solve the string comparison issue, but it's awkward to have to format that yourself just for GrowthBook.

We can fix this with 2 changes:
1. Introduce a `format` setting for string targeting attributing in GrowthBook.  Each format would provide it's own UI for entering values and be responsible for serializing it into a string value (e.g. adding/removing leading zeros)
2. Add SDK docs about how to store different attribute formats

```ts
new GrowthBook({
  attributes: {
    // Add leading zeros to semver strings
    semver: version.split(".").map(v => v.padStart(3, "0")).join("."),
    // Format dates in ISO format
    date: (new Date()).toISOString()
  }
})
```

We have to decide on how much padding to use.  With 3 digits, it allows for versions up to `999.999.999`

**Comment by ilyausorov** [comment]
🙏🙏🙏
P.S. We use the [semver](https://www.npmjs.com/package/semver) package to do the comparison client side, which if you also perhaps use can solve a lot of the decision making about how to support it and all these leading 0 questions? Perhaps an attribute can be of type "semver version" and then you just the server package to do the comparison?

**Comment by MarcoSantarossa** [comment]
Hi @jdorn , do you have some updates on this feature please?
