### ISSUE TITLE
[Feature] Option to return experiment and variation names from SDK endpoints

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#673]
### Description of Feature

Currently, the only way to identify an experiment in the SDK trackingCallback is via the `trackingKey` and variation array index:

```ts
function(experiment, result) {
  // trackingKey and array index
  console.log(experiment.key, result.variationId);
}
```

The improve logs and data usability, we should allow human-readable names as well for both the experiment and variations.  Ideally, you would be able to do:

```ts
function(experiment, result) {
  console.log(
    experiment.key,
    experiment.name,
    result.variationId,
    result.variationName
  )
}
```

This involves updating the SDKs to support these additional properties and changing our SDK endpoint to add them to the response.  We may want to make it optional on a per-endpoint basis.  Some users may not want to expose that info to client-side code for example.

**Comment by bttf** [comment]
Customer asked about this today
https://growthbookusers.slack.com/archives/C01T6Q0TEG3/p1694093853210739

**Comment by jdorn** [comment]
This is supported now as an SDK Connection setting
