### ISSUE TITLE
[Question] Best practices for changing/extenting an feature/experiment? 

### ISSUE THREAD

**Issue by iparker** [growthbook/growthbook#711]
Hello,

I have not much experience with a/b-testing - so I want to ask how you handle the following case:

You run an a/b-test with two variants (current/default variant v0 and another/new variant v1).

The new variant v1 does **not** win against the default variant, so you want to create another variant v2 to compare v0 against v2.

What is the recommended way to handle this?

Should I create a new feature flag? Or is it better to create a new variant in the existing feature and customize splitting to 50/50 for the variants v0/v2 (so the v1 gets a ratio of 0)?

And whats with the experiment? When it's a new feature there will be a new experiment. But when I change the feature with a new variant, do I have to add a new phase in the experiment to handle and differentiate this?

How do you handle this case?

Thanks for some help!

Best regards,

Timo

**Comment by Auz** [comment]
There are a few ways to handle this situation, and it depends a bit if you want to reassign all the users from the original experiment or keep the same bucketing.

1. You can just update the variation and code to show v2, with the same flag and over ride rule, and create a new phase of the experiment report. This will keep the same assignments. If some of your metrics  

2. Adjust the experiment rule of the feature with v0 and v2, and change the tracking key, which will cause it to reassign all users, and you could create a new experiment report. (you can also do this by making a new feature)

**Comment by lukesonnet** [comment]
One note is that just adding a new phase can suffer from carryover bias, so that's one additional reason to go with optino 2 above.

I'm going to close this as it's not a GH issue, but we should consider adding more FAQ and documentation around this to the docs, but we've tracked that internally already.
