### ISSUE TITLE
[Bug] Changing MSSQL port gives 'The "config.options.port" property must be of type number_'

### ISSUE THREAD

**Issue by emiel-veersma** [growthbook/growthbook#716]
When I was adding an MSSQL database as my first data source and changed the port, it gave the following error: "_The "config.options.port" property must be of type number_". This doesn't happen when I kept the port as default (1433), because it sends it as an integer then. But when I changed the value, it became a string and the form wasn't processed.

I think it can be fixed by casting the port value to an integer.

**Comment by Auz** [comment]
Thanks Emiel, we'll take a look
