### ISSUE TITLE
[Feature] Feature environment kill switch should require push or a user confirmation

### ISSUE THREAD

**Issue by avishail** [growthbook/growthbook#719]
### Description of Feature

In order to be consistent with every other feature modification that requires a push in order to take effect, the environment kill switch should also be pushed, or at least to be confirmed by the user with "are you sure" dialog. The kill switch is dangerous and an innocent click on the wrong spot can shut it down for the whole environment which isn't great.

### Related Issues

None

**Comment by jdorn** [comment]
This is supported now as an organization setting.
![image](https://github.com/growthbook/growthbook/assets/1087514/7b41ce75-8560-42e9-832a-50c9d7e24bc3)
