### ISSUE TITLE
[Feature] Easy way to re-order variations in an experiment

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#720]
### Description of Feature

If an experiment is set up with variations in the incorrect order for whatever reason, it's very difficult to fix later with the current UI.  When editing variations, we should allow drag and drop to reorder.

**Comment by mknowlton89** [comment]
@jdorn The only place I've seen that we can edit the variations of an experiment is via the feature flag "Edit" Modal. Is that what you are referring to?

For context, can you share why the order of the variations is important?

Also, I know you're working on joining Features/Experiments - Will my taking this ticket on while you're in the middle of that introduce any potential issues or big merge conflicts?

**Comment by mknowlton89** [comment]
Spoke to Jeremy re: the questions above, this is just updating the order on the front-end, as the first variation is the control.
