### ISSUE TITLE
[Feature] New attribution model - "Experiment Duration"

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#721]
### Description of Feature

We currently have two attribution models (`First Exposure` and `All Exposures`) that help determine how we calculate conversion windows.

We should add a 3rd model - `Experiment Duration` which hard-codes the end of the conversion window to be equal to the experiment end date.  This will in essence ignore the conversion window settings for metrics and vastly simplify the SQL.

To summarize the different models:

| Attribution Model   | Number of Conversion Windows | Conversion Window Start                | Conversion Window End                              |
|---------------------|--------------------|----------------------------------------|----------------------------------------------------|
| First Exposure      | 1             | First Exposure Date + Conversion Delay | Conversion Window Start + Conversion Window Length |
| All Exposures       | Multiple           | Each Exposure Date + Conversion Delay  | Conversion Window Start + Conversion Window Length |
| Experiment Duration | 1             | First Exposure Date + Conversion Delay | End of Experiment                                  |

**Comment by hildeirin** [comment]
Would be so awesome to see this feature come to life soon! 😊 More and more of our teams are needing this

**Comment by jdorn** [comment]
Good news, we have a big SQL refactor coming soon that solves this issue.  We decided to get rid of the All Exposures model and replace it with with an Experiment Duration model. This has huge performance benefits (up to 2x faster queries) and makes it easier to support CUPED variance reduction (also coming soon)

 #1066
