### ISSUE TITLE
[Feature] Cron Timezone UI Clarification

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#733]
Right now, when users schedule metric/experiment updates, it uses system time, which is UTC in docker containers by default. It is unclear from our UI which timezone will be scheduled. It would be helpful if the UI would either explain what timezone it is using or give actual date/time of when the cron job will be run.

**Comment by bttf** [comment]
@Auz I pushed a PR addressing this ... I'm not 100% if it's what you are looking for, here is a screenshot
![image](https://user-images.githubusercontent.com/2374625/206285824-30375b11-8268-45a6-a63c-70f6f1a1d6e0.png)
