### ISSUE TITLE
[Bug][Question] : Denominator isn't in the config?

### ISSUE THREAD

**Issue by benbenbang** [growthbook/growthbook#736]
### Summary

Hi team,

we've configured a denominator in our preproduction environment, but after we downloaded the config, we cannot find it anywhere else. Could you please help us to confirm if it's due to misconfiguration or a bug? thank you

- info
    - Build: [5cefb86](https://github.com/growthbook/growthbook/commit/5cefb860fb8206d4561cb2fb4c1a28fd28a9638a) (2022-10-09)
    - backend: vendor version MongoDB 

### Expected

After download the config, we should see denominator in the metrics section

**Comment by mknowlton89** [comment]
@benbenbang Thank you for creating this issue - I just merged an update that now includes the denominator property, along with a number of additional properties. Please let me know if you experience any other issues.

**Comment by Auz** [comment]
Hi @benbenbang - this change is already live on our Cloud. If you are self hosting, you can update to the latest version to see the changes.

**Comment by benbenbang** [comment]
@Auz 👋🏻 Cool, that's great news! Thanks a lot!
