### ISSUE TITLE
[Feature] Marketing Pop-Up builder

### ISSUE THREAD

**Issue by pahaz** [growthbook/growthbook#742]
### Description of Feature

From one project to another I meet the same marketing needs.
They need some SaaS tools for marketing popup experiments. 
It's similar to the feature experiment bug for marketing purposes.
There are lots of tools for that but no self-hosted open-source solutions.

You can be the first!

**Comment by lukesonnet** [comment]
I wonder if this can be solved with our [visual editor](https://docs.growthbook.io/app/visual)! I think it might, in which case I'll close this issue unless someone wants to re-open it.
