### ISSUE TITLE
[Feature] Allow features to belong to multiple projects

### ISSUE THREAD

**Issue by bgentry** [growthbook/growthbook#752]
### Description of Feature

We run complex infrastructure with multiple product areas. These are architecturally separated, and sometimes live in different datacenters. In order to avoid bloating our feature definition JSON, we've been separating features by Project so that particular project areas can only receive the list of features _they_ care about, rather than the list of every single feature defined in the system. This works well most of the time.

Where this breaks down, though, is when we need a single feature flag to be available across multiple areas of our infrastructure. While this isn't the default, sometimes it's desirable. We might want our customer-facing user interface to be able to resolve a feature flag, as well as some deep internal subsystem that we'd consider a separate Project where features don't normally overlap.

Please note that this is not covered by the existing Environments functionality. I'm referring strictly to our production environment where a given feature might have multiple Projects which it is relevant for, even though _most_ of our features would only be relevant for a single Project.

My understanding is that the only way to do this today would be to not assign features to projects at all, and to not filter the SDK Endpoint request by `projectId`. We're afraid this approach won't scale, because it means we'd be making many user interface feature definitions available to distant subsystems that don't care about those features or make use of them. If the relationship between Features and Projects was changed from a 1:many to a many:many relationship, this would allow us to keep the separation most of the time when we want it, but also allow us to share features between projects where appropriate.

Please let me know if a more concrete example would be helpful to illustrate this use case. Thanks!

### Related Issues

None

**Comment by jdorn** [comment]
Closing this in favor of #1400
