### ISSUE TITLE
[Bug] Experiment coverage of 0% causes 100%

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#756]
Features with an experiments rule with coverage set to 0% cause 100% effective coverage when the feature rule is evaluated. In the JS SDK, we have a line that generates to:

`const ranges = getBucketRanges(numVariations, experiment.coverage || 1, experiment.weights);`

Which causes experiments which are set to 0% to have an effective coverage of 100%. The offending line seems to be here: 

https://github.com/growthbook/growthbook/blob/main/packages/sdk-js/src/GrowthBook.ts#L540

**Comment by jdorn** [comment]
We should add a test case for this and also update the other SDKs as well as our build-your-own docs.

**Comment by bttf** [comment]
The fix for the JS SDK is in review. I could use assistance in understanding how to best address other SDKs, or the build-your-own docs
