### ISSUE TITLE
GA4 support with growthbook

### ISSUE THREAD

**Issue by VedantParth89** [growthbook/growthbook#759]
Hello Team,

Is GA4 support will be there with system ?

We are planning to integrate growthbook with B2C product.

Regards,
Parth Vedant

**Comment by Auz** [comment]
Hi Vedant - We support GA4 when exporting to a data warehouse. The Google API has too many limits for our advanced usage, where as using a SQL db is a lot more powerful. You can pretty easily export GA4 to BigQuery: https://support.google.com/analytics/answer/9358801?hl=en 

Once that's setup, you can use our click on GA4 from the add data source, and follow the steps.

**Comment by VedantParth89** [comment]
Thank you very much for the update.

*Regards,*
*Parth Vedant*
Senior Business Analyst


www.gelato.com
Email: ***@***.***
Mobile: +91 9904030689
