### ISSUE TITLE
[Bug] All SDKs - Upgrade to test cases version 0.2.3

### ISSUE THREAD

**Issue by bttf** [growthbook/growthbook#814]
### Summary

There was a bug fixed recently in the JS SDK relating to experiments with coverages set to 0%

This task is to apply [this test case](https://github.com/growthbook/growthbook/pull/795/files#diff-24e2e46dbe5570384eac6c4f19a956458099bc99dbc438ff0973d415c198888aR2735-R2748) to our other SDKs to ensure it is not occurring on those as well

List of all SDKs: https://www.notion.so/SDK-Feature-Parity-4e83abf6d76d4537b5297408e1f67d01

**Comment by tinahollygb** [comment]
We are tracking this on a per SDK basis in their own issues.
