### ISSUE TITLE
[Enhancement] Update type of rule input in RuleModal styles so it's clear it's disabled

### ISSUE THREAD

**Issue by mknowlton89** [growthbook/growthbook#822]
### Description of Feature
When editing an override rule, I can't change the type of rule. Perhaps this is intentional, but the UI suggests that the field is actually editable:

![](https://user-images.githubusercontent.com/7927873/205716182-06f0de17-cf7e-450c-823d-20e87175a9f9.png)

There are some one-off rules in global.scss that add graying out for <select> fields. Perhaps you could piggyback on these rules, extend them to your input field?

<img width="690" alt="Screen Shot 2022-12-08 at 2 56 27 PM" src="https://user-images.githubusercontent.com/75274610/206555114-5f52c525-242b-4f82-af0c-5db7f2275f53.png">

**Comment by bttf** [comment]
This seems to be addressed now ... good to close @mknowlton89 ?

<img width="833" alt="Screen Shot 2022-12-23 at 2 30 01 PM" src="https://user-images.githubusercontent.com/2374625/209403002-34e660a2-ba2f-426b-8a02-1194018252b4.png">

**Comment by mknowlton89** [comment]
Interesting! Yup - looks good to close!
