### ISSUE TITLE
[Feature] Support different methods of attributing metric conversions to dimension values

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#831]
### Description of Feature

If you select a `device_type` dimension on experiment results and a user visited your site on both mobile and desktop, there are multiple ways we could handle this, but it's not clear which method is being used and there's no way to customize this behavior.

Example:

- Day 1: User views experiment on desktop
- Day 3: User views experiment on mobile
- Day 4: User converts on mobile

|  | Method | User | Conversion |
| ---- | ---------- | ------- | --------------|
| 1 | First dimension | desktop only | desktop only |
| 2 | All dimensions, unrestricted conversions | desktop and mobile | desktop and mobile |
| 3 | All dimensions, restricted conversions | desktop and mobile | mobile only |

Currently, GrowthBook always uses method 2

**Comment by lukesonnet** [comment]
We also should consider:
|  | Method | User | Conversion |
| ---- | ---------- | ------- | --------------|
| 4 | First dimension | desktop only | desktop and mobile |

Which would be relatively easy to implement, and would reduce the risk of bias when analyzing dimensional splits.

**Comment by lukesonnet** [comment]
Note: I believe we now do my #4 after the refactor mentioned above.

**Comment by jdorn** [comment]
Closing this as completed
