### ISSUE TITLE
[Feature] Serve uploaded variation screenshots using private S3 bucket

### ISSUE THREAD

**Issue by rowolff** [growthbook/growthbook#857]
### Description of Feature

Using the S3 upload method requires the S3 bucket to be publicly accessible. For organisations where public buckets are disabled as per security guardrails, we would like to use the S3 upload method with buckets that have `Block Public Access` enabled on the AWS account level.

#### Ideas
* generate a pre-signed url not just for upload, but also for viewing OR
* require a CloudFront distribution to be in place that can serve the images

**Comment by sweethuman** [comment]
This would also be great for users which use Generic S3 offerings that don't public buckets the same way AWS S3 has.
