### ISSUE TITLE
[Bug] Can't publish draft changes - Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by wjbeau** [growthbook/growthbook#866]
### Summary

I have 3 feature flags defined, and 3 environments.  I've added a Forced rule to disable a feature flag in one of the environments but when I go to publish the draft changes I get a message:

`Cannot read properties of undefined (reading 'forEach')` and the changes aren't published.

#### Expected Behavior

The changes should be published

#### Current Behavior

<img width="1522" alt="Screenshot 2022-12-29 at 16 25 17" src="https://user-images.githubusercontent.com/4557711/209981265-58a685c4-d03e-4097-855c-89e86164b075.png">

**Comment by Auz** [comment]
Thanks for reporting this issue. The fix will be live shortly.

**Comment by wjbeau** [comment]
> Thanks for reporting this issue. The fix will be live shortly.

Amazing thanks!
