### ISSUE TITLE
Viewing the experiment report from the feature details breaks for draft features

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#875]
Steps to reproduce:
* Create a feature flag with no rules
* Add an experiment rule to one environment
* Before publishing it, click on the 'view results' link
* Create the experiment report
* Navigate back to the feature detail page and click 'view results' again

Expected result: Navigates back to the experiment details we just made
Actual result: Opens a new modal to make a new experiment report

**Comment by jdorn** [comment]
This is fixed with the recent feature/experiment refactor
