### ISSUE TITLE
Self-hosted SSO (enterprise feature)

### ISSUE THREAD

**Issue by jdorn** [growthbook/growthbook#88]
Support SSO for self-hosted deployments (Google, Okta, Auth0, etc.).  This will be our first Enterprise feature that is not covered under the MIT license

Changes
-  New `packages/enterprise` directory with non-open source license (plus change root level LICENSE to reference this)
-  Enterprise license key support
-  New environment variable `AUTH_METHOD` which defaults to `local`, but can be set to `saml` or `google` instead.
-  New environment variables for Google auth (`GOOGLE_OAUTH_KEY` and `GOOGLE_OAUTH_SECRET`)
-  New environment variables for SAML auth (`SAML_ENTITY_ID`, `SAML_ACS_URL`, `SAML_X509_CERT`, `SAML_ATTR_EMAIL`, and `SAML_ATTR_NAME`)
-  Redirect to IdP instead of showing local auth form
-  Endpoint to process Google auth response
-  Endpoint to process SAML auth response
-  Remove "edit profile" and "change password" functionality when using SSO
-  Hook up logout button

**Comment by dhavalpowar** [comment]
@jdorn any update on when this is expected to hit the self-hosted version? I'm really looking forward to this feature.

**Comment by jdorn** [comment]
Support for this was merged last month in #466 .  Forgot to close this issue
