### ISSUE TITLE
[Bug] Experiments with 6, 7, and 10 variations can't be saved

### ISSUE THREAD

**Issue by mknowlton89** [growthbook/growthbook#880]
### Summary

When creating an experiment, if you have 6,7, or 10 variations (and likely others) you're unable to save. The weight of the variations add up to above 1, and there is no way to adjust a single variation down in order to save it, as adjusting 1 variation down, adjusts another variation up on a 1:1 scale.

<img width="789" alt="Screen Shot 2023-01-06 at 12 17 12 PM" src="https://user-images.githubusercontent.com/75274610/211064398-04467032-9498-4f5e-ab83-640e65b2884b.png">

This is not likely something users bump in to often, so not super high priority, but I'd be curious if there was a way to handle this more gracefully.

#### Expected Behavior

You should be able to adjust a single variation without affecting other variations, so you can run an experiment with all number of variations.

#### Current Behavior

Adjusting 1 variation down, adjusts a different variation up, so you're not able to save an experiment with 6,7, or 10 variations. (Likely others, I just didn't try any higher than 10).

**Comment by tinahollygb** [comment]
This is not reproducible in the current code. When I try to do the example variations you've specified, I get a validation error that variation keys must be unique (you have three instances of variation ID = 1).
