### ISSUE TITLE
[Bug] Broken vertical guides in CI plot when metric names are long

### ISSUE THREAD

**Issue by lukesonnet** [growthbook/growthbook#884]
### Summary

When metric names are long, the vertical guides in the CI plot are broken.

#### Expected Behavior

The lines should be continuous through the plot, but they are broken as you can see below: 
<img width="940" alt="image" src="https://user-images.githubusercontent.com/5298599/211427834-c67fb4a3-7011-4d84-8f78-38e3bce5b4ec.png">

From inspecting the table, it seems the `aligned-graph` div does not fill the `compact-graph` td that it lives within.

**Comment by jdorn** [comment]
This should no longer be an issue with the latest experiment results redesign
