### ISSUE TITLE
[Feature]  Allow currency to vary by user locale or by metric

### ISSUE THREAD

**Issue by lukesonnet** [growthbook/growthbook#908]
### Description of Feature

Currently, in https://github.com/growthbook/growthbook/blob/9b7315f78f06a8f722285c49095920e6d0cec36d/packages/front-end/services/metrics.tsx, it appears that `formatConversionRate` always uses USD, but we could allow for different customizable currencies set at the metric level, or currencies depending on user locale.

**Comment by lukesonnet** [comment]
Closed by #1275 !

**Comment by xgumara** [comment]
This does not allow to change currency by metric, right?
