### ISSUE TITLE
Flutter Client Library for GrowthBook

### ISSUE THREAD

**Issue by ngocatfika** [growthbook/growthbook#93]
Flutter is a fast-growing ecosystem. I find that there will be lots of merit to help grow Growthbook if we have a Flutter Client Side Library!

**Comment by jdorn** [comment]
Hi!  Would you have any interest in helping to build this for the community?  Our client libraries are usually only a few hundred lines of code and the structure is documented at https://docs.growthbook.io/lib/build-your-own

**Comment by ngoctranfire** [comment]
@jdorn That sounds great. I'll look into this. This looks like a great framework and I definitely want to look into this!

**Comment by tinahollygb** [comment]
We have a community-contributed Flutter SDK now: https://docs.growthbook.io/lib/flutter

If you find any issues with it, please add an issue to that repository.
