### ISSUE TITLE
[Bug] Visual Editor - Missing Required Script

### ISSUE THREAD

**Issue by mitchfitzsimmons** [growthbook/growthbook#932]
### Summary

I am getting a missing required script error for the visual editor despite having all the code live in the website. 

#### Expected Behavior

I expect to be able to use the visual editor to create a web experiment.

#### Current Behavior

I am getting an error saying that there is a 'missing required script'.

![image](https://user-images.githubusercontent.com/19276741/213948757-8deae968-6dcb-48b9-bb20-19e635d886eb.png)

**Comment by dionvogliqi** [comment]
I also get the same problem. It works on staging but it fails on production with the same code.
