### ISSUE TITLE
Update MongoDB node driver to 4.1+ to support MongoDB Atlas

### ISSUE THREAD

**Issue by kelvinsi** [growthbook/growthbook#935]
We'd like to use Growthbook with Mongo Atlas's serverless product [which requires v4.1 or higher](https://www.mongodb.com/docs/atlas/reference/serverless-instance-limitations/#minimum-driver-versions-for-serverless-instances)

Currently the package specifies 3.7 https://github.com/growthbook/growthbook/blob/214da6b8ad8add5643f505ed609f3fa5b6fa637f/packages/back-end/package.json#L54

**Comment by gandarez** [comment]
Is there any plan to release it soon? I can't get it working with MongoDB Atlas on my k8s cluster.
