### ISSUE TITLE
[Feature] Add custom SSL certificate to Mongo connection

### ISSUE THREAD

**Issue by Auz** [growthbook/growthbook#941]
The Mongoose connection method has the ability to set sslCA paths and other SSL/TLS options but we do not expose them via environment variables. This means that users using self-signed CAs or trying to connect to DocumentDB using TLS may not be able to do it.

**Comment by Auz** [comment]
You can connect using a custom certificate using the path from the connection string: 
`‘mongodb+srv://username:password@host/db_name?authSource=admin&replicaSet=repliasetname&tls=true&tlsCAFile=/root/ca-certificate.crt’`

I'm going to close this issue - but please reopen if this does not solve the problem.

**Comment by egor-xyz** [comment]
@Auz I'll check today. Thanks
