### ISSUE TITLE
[Bug] setting up override rules for feature flag if id is equal to multiple ids listed (vunerability)

### ISSUE THREAD

**Issue by Stradivario** [growthbook/growthbook#954]
### Summary

First of all thank you very much for this project keep up the good work!

1. I setup the project locally using docker-compose just to test it out. 
2. Everything was working smoothly and it spin up as expected on port 3000.
3. I registered account and i setup my first feature flag called `enable-lambdas` 
4. I decided that `enable-lambdas` feature flag will be explicit only for several users with id `1,2,3,4,5,6`
5. I have connected my frontend application using the SDK.
6. I setup user Attributes `growthbook.setAttributes({ id: 7 });`

So what i have noticed is that i am user which doesn't know anything about the system and other users with enabled feature flags but when i open the request tab i am seeing this view

![Screenshot from 2023-01-30 10-55-31](https://user-images.githubusercontent.com/19847933/215434113-b723da53-a041-42c5-b853-4d2eee1be277.png)

So how is it even possible that the growthbook backend returns information for the feature flag and its forced values represented by ID's  ?

So imagine that i have a big website with 10 000 users and 5000 users have enabled feature `enable-lambdas` the rest of the users 5000 that doesn't know anything about the other 5000 users will have information of the ID's of the users that have enabled a particular feature flag.
As far as i can think of this to me smells like a vulnerability.

#### Expected Behavior

I am expecting to see in the request only is feature flag enabled or not and based on the user Attributes which are send to growthbook API the backend to be able to return only boolean values for the feature flag and to be stripped out of information for other id's.

Also if i decide to add value to my 10 000 users how big this request can become ?  

#### Current Behavior

It gives me all of the information for the user ids and feature flags that are enabled for a particular user even if i am not registered user in the platform.

Am i doing something wrong ? Am i missing something ? Is this the intended behaviour ?

Cheers guys and wish you a great day/night! :)

**Comment by GitHelge** [comment]
I also thought about this today but i guess thats the way the package works ... everything is client-side based. You only get the rules, but the browser/server decides what to do with the rules. We use encoded ids to reduce the potential security risks.

**Comment by bryce-fitzsimons** [comment]
In short, this is by design: The SDK payload always carries the information necessary to evaluate its rules in whatever context it's used in. In a backend SDK the environment is secure, but for frontend you end up exposing your rules and saved groups. Some options:
- Mitigate the risk by using secure attribute hashing and encryption, which in tandem offer strong obfuscation.
- Eliminate the risk by moving evaluation to a backend SDK and shipping the evaluated flag values down to the frontend rather than evaluating on the front end.
- Stay tuned for the upcoming "Remote Evaluation" feature that we are launching soon that provides backend security for frontend SDKs.

**Comment by GitHelge** [comment]
So if I want to activate a feature for 20000 specific users, I have to send each user megabytes of data in rules? Or is there something I am missing? I need to know for which users the flag is activated before to send them emails as well. 

Is there an update on the remote evaluation?

**Comment by bryce-fitzsimons** [comment]
Remote evaluation was launched on October 4, 2023. You need to set it up per SDK Connection, and you must host either GrowthBook Proxy or another backend evaluation endpoint in order for it to work.

You may also be interested in runtime saved groups or the upcoming "big groups" (no ETA on this one yet).
