### ISSUE TITLE
[Bug] Tool-tip text is unreadable when in dark mode

### ISSUE THREAD

**Issue by rahul-berbix** [growthbook/growthbook#955]
### Summary

When the dashboard is in dark mode, it is almost impossible to read text on tool-tips. A couple examples include the tool-tip on the "Percent Change" column and the "Risk of Choosing" column

#### Expected Behavior

The text should be readable

#### Current Behavior

The text is very faint
![image](https://user-images.githubusercontent.com/105461294/215547302-ffcc7cfa-9466-4f53-8a92-1f9921be8a43.png)

**Comment by tinahollygb** [comment]
This no longer appears to be an issue. We did fix some dark mode bugs a while ago, this one may have already been caught. 

<img width="406" alt="image" src="https://user-images.githubusercontent.com/113377031/235543432-2dc1b2bd-d6db-4440-916f-bfafa28487bc.png">

Feel free to reopen if it's still an issue.
