### ISSUE TITLE
[Bug/Question] autoRefresh not working as expected (NodeJS)

### ISSUE THREAD

**Issue by viniciusln** [growthbook/growthbook#960]
### Summary

I'm trying out the sdk (in NodeJS) and the `autoRefresh` option does not seem to be working properly, or maybe I'm misunderstanding the concept (please help me understand if that's the case).

#### Expected Behavior

After updating a feature value (on/off) in the dashboard, the `isOn` function should return the correct/updated value.

#### Current Behavior

The `isOn` function is returning the previous value. To get an updated value, I need to `loadFeatures` again, or call `refreshFeatures` (in both cases I need to `skipCache=true`).

**Comment by Xyr2** [comment]
I have the same issue with a self hosted instance. Do you also host gb yourself? Does it need some special setup to make the updates work with selft hosted instances?
The state in the gb backend is `connected` for my SDK endpoint...

**Comment by viniciusln** [comment]
I tried both self hosted and their cloud solution, both behave the same.
