### ISSUE TITLE
Fullstory as Datasource

### ISSUE THREAD

**Issue by msubodh** [growthbook/growthbook#977]
Hi, do you have plans on adding Fullstory as a datasource? Thanks.

**Comment by Auz** [comment]
Fullstory has an API, but I have a feeling that it's not going to allow us the right level of data. However, you can use their data destinations feature: https://help.fullstory.com/hc/en-us/articles/6295300682903-Data-Destinations to export data to Snowflake or BigQuery, and then connect GrowthBook to one of those. If you get a destination set up and need help with the queries feel free to reach out to us, and we can help you get it set up.

**Comment by Auz** [comment]
We have added support for fullstory via the data destination and added data schema for generating the initial queries. Let us know if you have any issues with it.
