### ISSUE TITLE
[Feature] Add the ability to view the history/audit of user actions in GrowthBook UI

### ISSUE THREAD

**Issue by apilyugina** [growthbook/growthbook#980]
### Description of Feature

Please add the ability to view the history/audit of user actions in GrowthBook UI.

### Related Issues

For all user actions in GrowthBook, I would like to see records in the history / audit to answer the question "when / who / what I did in GrowthBook?”

I can give an example of records:
- user log is system
- create and experiment 
- configures data source
- changes some feature flags
- updates experiment 
- log out

**Comment by jdorn** [comment]
This exists now on the **Settings -> Logs** page.
