### ISSUE TITLE
[Bug] Lack of documentation around environments

### ISSUE THREAD

**Issue by mochetts** [growthbook/growthbook#988]
### Summary

How do I set environments in a growthbook setup script? I'm using React:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/3678598/217664049-1e1bd98f-2663-49e6-b2d2-9c72f703034c.png">

This are the docs:
https://docs.growthbook.io/app/features#environments

I have a local env that is hooked in with growthbook, now I want to tell growthbook that this is my local environment but I can't seem to be able to do so

#### Expected Behavior

Better docs around environments. How to reference environments in code.

#### Current Behavior

No docs

**Comment by ycfeaturebyte** [comment]
i think that is not how it works, it doesn't support passing environment attribute.

in your dashboard, you can go to Features > SDKs page. When creating a new SDK connection, you can specific which environment. Which mean, different environment will have different GROWTHBOOK_CLIENT_KEY.

**Comment by mochetts** [comment]
@ycfeaturebyte so what's the purpose of having FFs being enabled / disabled depending on this environment value?

**Comment by tinahollygb** [comment]
@mochetts client keys are unique to environments. When you configured your key you should've seen an environment picker. 

New SDK config:

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/113377031/235516174-095934b8-42d6-4df1-ab52-7e39deea154e.png">

Legacy SDK endpoints:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/113377031/235516288-478a8319-2bbd-425c-9de7-82a99d190d7e.png">

You can learn more about environments here: https://docs.growthbook.io/app/features#environments

You can access your environments in the app here: https://app.growthbook.io/environments
